"""Shared bit-parity corpus used by the binary-WAV test and tooling.

The same list is consumed by:

- ``tests/parity/test_binary_wav_parity.py`` -- asserts each prompt
  renders to a byte-identical WAV vs the shipped DECtalk binary.
- ``scripts/diagnose_audio.py`` (with ``--bit-parity-corpus``) --
  materialises the corpus into ``docs/audio_samples/`` for human
  inspection and committed-into-repo audio comparison artefacts.

Edits to this tuple affect both paths.
"""

from __future__ import annotations

CORPUS: tuple[str, ...] = (
    # Original baseline corpus.
    "hello world",
    "the quick brown fox",
    "she sells sea shells",
    "one two three four five",
    "supercalifragilisticexpialidocious",
    "[:rate 250] testing one two three",
    "DECtalk version 6.2.0",
    "this is a test, with a comma, and a period.",
    # Numbers and decimal.
    "the answer is 42",
    "3 point 14",
    "one hundred and one dalmatians",
    "1234567890",
    # Punctuation variants.
    "hello! how are you?",
    "wait... what just happened?",
    "yes; no; maybe.",
    # Inline-command rate.
    "[:rate 100] slow",
    "[:rate 400] fast speech",
    # Inline-command voice presets -- exercise the 9 canonical voices.
    "[:nb] betty speaking",
    "[:nh] harry speaking",
    "[:nf] frank speaking",
    "[:nd] dennis speaking",
    "[:nk] kit the kid",
    "[:nu] ursula speaking",
    "[:nr] rita rough",
    "[:nw] wendy whispery",
    # Spell-out cases (short all-caps).
    "FBI",
    "NASA",
    "USA",
    "MIT",
    # Common English phonotactics.
    "judge thought rhythms",
    "knight light right",
    # Mixed punctuation with abbreviations.
    "Dr. Smith said hello.",
    # Long-ish utterance.
    "the rain in spain falls mainly on the plain",
    # Syllabic-L (US_EL) coverage: word-final L after consonant.
    "apple table bottle",
    "a little bottle",
    "middle of the road",
    # Syllabic-N (US_EN) coverage: word-final N after consonant.
    "button sudden reason",
    "broken eaten",
    # -ING reduction (AH0/IH0 -> ix before NG).
    "morning evening running meeting",
    # WH-question intonation: ``?`` -> ``.`` token when the sentence
    # contains a wh- word; yes/no questions keep the ``?`` marker.
    "how?",
    "what time is it?",
    # Function-word destressing of ``to`` (SBOUND + PPSTART + T + UH).
    "to bed",
    "walk to the store",
    # Function-word destressing of ``for`` (SBOUND + PPSTART + F + ER).
    "for now",
    "for ever",
    # Root-internal S after R must NOT voice to Z (``course`` / ``horse``
    # stay with final S; inflectional ``cars`` / ``sells`` voice to Z).
    "of course",
    "the horse",
    "cars and trucks",
    # First-verb stress (``are``/``had``/``is``/``was``/``were``/``will``)
    # at sentence start gets secondary stress; mid-sentence stays unstressed.
    "is it raining",
    "this is good",
    "it was good",
    # Stem-stripping plurals: lookup falls back to the singular stem
    # (``seconds`` -> ``second``), with syllabic-N / voicing applied.
    "two seconds",
    "three reasons",
    "five days",
    "two trees",
    # ``-er`` agentive / comparative suffix: stem stripping.
    "later",
    "faster",
    # ``-ed`` past-tense suffix: stem stripping + voicing/epenthesis rule
    # (T after voiceless, IX+D after T/D, D after voiced).
    "walked",
    "talked",
    "needed",
    "loved",
    "liked",
    # ``-ing`` gerund / present-participle suffix: stem stripping + IX NG.
    "walking",
    "talking",
    "jumping",
    "running",
    # ``'s`` contraction (``that's`` = ``that is``): strip the apostrophe
    # and append S (voicing handled by the encoder).
    "that's",
    "it's",
    "what's",
    "there's",
    # ``-ness`` noun-forming suffix: stem + ``N IX S``.
    "darkness",
    "sadness",
    "happiness",
    # ``-ful`` / ``-less`` adjective suffixes.
    "helpful",
    "helpless",
    "careless",
    # ``-ment`` noun-forming suffix.
    "payment",
    "shipment",
    "statement",
    # ``-tion`` / ``-sion`` (AH0+N -> IX+N after SH/ZH/CH/JH/R).
    "nation",
    "mission",
    # ``-est`` superlative suffix.
    "smallest",
    "oldest",
    "fastest",
    "biggest",
    # Y -> I morphological alternation in plurals (``cities`` -> ``city``).
    "cities",
    "babies",
    "cherries",
    # Y -> I in -ed past tense (``studied`` -> ``study``).
    "studied",
    "tried",
    # Mono-syllabic AH0+S (``us``) keeps AX; multi-syllabic uses IX.
    "us",
    # ``-n't`` contractions: N becomes syllabic-EN before the trailing T.
    "didn't",
    "couldn't",
    # AH0 + F + L word-final (the ``-iful`` connector): AH0 -> IX.
    "beautiful",
    # -OUS suffix: AH0+S -> AX after M/V/F/etc. obstruents; -> IX after
    # L/N/R sonorants.
    "famous",
    "nervous",
    "jealous",
    # ``-it`` suffix: AH0+T word-final -> IX+T when the stressed vowel is
    # a short monophthong (visit / limit / edit / audit). Diphthong-stressed
    # private / climate keep AX+T.
    "visit",
    "limit",
    "private",
    # Post-stress AH0+N+T after R -> IX (``parent`` -> ``p ' eyr ixn t``).
    "parent",
    # N -> NG velar assimilation before K / G (``pink`` -> ``p ' ihnxk``).
    "pink",
    "tank",
    # -ness with LTS-fallback stem (firm / odd not in lexicon).
    "firmness",
    "oddness",
    # Longer phrasal corpus -- exercises mid-sentence first-verb destressing,
    # function-word reductions, and inflectional morphology together.
    "a good day",
    "three nice gifts",
    "the cat is happy",
    "the dogs ran",
    "you are welcome",
    "an apple tree",
    # Hyphenated compounds: emit ``#`` syllable-break instead of word break.
    "forty",
    "forty-two",
    "twenty-one",
    "self-taught",
    # Teen words: ``*`` MBOUND marker before T+IY+N. Literal forms use
    # secondary stress on IY; digit-expanded forms use primary stress.
    "fourteen",
    "fifteen",
    "sixteen",
    "eighteen",
    "15",
    "18",
    # Sibilant-final plurals: IX+Z epenthesis (classes / horses / roses).
    "classes",
    "horses",
    "kisses",
    "foxes",
    # AH0+Z after sibilant reads as IX+Z (sibilant 3rd-person sg -es).
    "fixes",
    "fishes",
    "watches",
    # M-in-cluster + AH0+S -> IX (``christmas`` -- SM cluster, IX).
    # M-after-vowel + AH0+S -> AX (``famous`` -- EY+M, AX).
    "christmas",
    # ``-ly`` adverb suffix: consonant-final stem + L + IY0.
    "friendly",
    "softly",
    "badly",
    "quickly",
    # ``-it`` short-vowel rule now covers IY / UW tense monophthongs too.
    "spirit",
    # Number / teen edge cases.
    "eleven",
    "thirteen",
    "13",
    # -tion / -sion suffix: stem-strip + SH + AH0 + N.
    "pension",
    "mansion",
    "tension",
    # Syllabic-N before word-final D (``thousand`` -> ``th' awz end``).
    "thousand",
    "second",
    # More multi-word phrasal coverage.
    "a good idea",
    "three small dogs",
    "open the windows",
    "two cats and three dogs",
    # Multi-syllabic AH0+Z (always) -> IX; monosyllabic (was) -> AX.
    "always",
    # Multi-syllabic AH0+K / IH0+K word-final -> IX (the -IC suffix).
    "music",
    "classic",
    "panic",
    # Multi-syllabic AH0+D word-final -> IX (-ID suffix), gated to
    # exclude liquid clusters (``hundred axd``) and vowel prev
    # (``period iyaxd``). Also fires for the plural ``methods``.
    "method",
    "methods",
    # AH0+V (-ive) / AH0+SH (-ish) / AH0+P (-up) / AH0+F (-iff) /
    # IH0 variants of same.
    "active",
    "passive",
    "creative",
    "finish",
    "radish",
    "syrup",
    "gossip",
    "mastiff",
    "cousin",
    "robin",
    # SH/ZH/CH/JH + AH0 + S -> IX (``conscious``, ``precious`` if in lex).
    "conscious",
    # More multi-word phrasal coverage with combined rules.
    "the lights are on",
    "random things",
    "fast cars",
    "busy bees",
    "social media",
    # AH0+N+T word-final -> IX regardless of preceding consonant.
    "silent",
    "distant",
    "patient",
    # VPSTART verb expansion: many common verbs now get the ``)`` marker.
    "we should go",
    "they will see",
    "you can ask",
    "thank you",
    "i think so",
    "see you tomorrow",
    "i want some",
    "we know better",
    "they sing songs",
    "she put it down",
    # More sentences with VPSTART verbs.
    "asked a question",
    "wanted to know",
    "told the truth",
    "thinking about",
    # -ENT / -ANT words: T+AH0+N+T / K+AH0+N+T / L+AH0+N+T -> IX.
    "constant",
    "talent",
    "vacant",
    # Possessive 's after sibilant -> IX+Z (judge's, fox's, horse's).
    "judge's",
    "fox's",
    "horse's",
    # -ORY / -ERY / -ARY: ER0+IY0 reads as ``rriy`` syllabic-R.
    "factory",
    "history",
    "mystery",
    "battery",
    # MBOUND ``*`` from per-entry dictionary marker (compound morphology).
    "house",
    "birthday",
    "notebook",
    "lighthouse",
    "old house",
    "happy birthday",
    # More VPSTART verb prompts.
    "i can hear you",
    "we live here",
    # AM as a sentence-internal verb gets the ``)`` marker.
    "i am happy",
    # MADE (past of MAKE) is form-classed as a verb in C's main dic.
    "made",
    # Compound words whose C dictionary entry carries an internal
    # ``*`` MBOUND marker. Post-MBOUND vowels stay unreduced (compare
    # ``everything`` -- C emits ``thihnx`` not ``thixnx``).
    "everything",
    "everyone",
    "anywhere",
    "sometimes",
    # Onset-cluster coverage (str-/spl-/scr-/spr-/thr-/bl-/br-).
    "strong",
    "street",
    "splash",
    "screen",
    "spring",
    "throw",
    "through",
    "bright",
    "bread",
    # AW / OY diphthong coverage.
    "town",
    "down",
    "south",
    "sound",
    "voice",
    "choice",
    "noise",
    "coin",
    # Silent-letter onsets (kn-/wr-) and -ough/-ought spellings.
    "knife",
    "knee",
    "write",
    "wrong",
    "would",
    "could",
    "should",
    "though",
    "tough",
    "enough",
    "cough",
    # WH-question words (single-word utterances; the ``?`` question
    # marker handling is exercised via "how?" / "what time is it?").
    "who",
    "where",
    "when",
    "why",
    "which",
    # ``-er`` agentive nouns: stem-strip + ``rr`` emit.
    "teacher",
    "singer",
    "winner",
    "runner",
    "driver",
    "player",
    "reader",
    # Sibilant-final plurals (IX+Z epenthesis).
    "bushes",
    "buses",
    "boxes",
    "dishes",
    "pages",
    "places",
    "faces",
    # More ``-ing`` gerunds.
    "swimming",
    "reading",
    "writing",
    "playing",
    "singing",
    "cooking",
    "sleeping",
    "eating",
    "drinking",
    "feeling",
    "looking",
    "moving",
    "going",
    # More ``-ed`` past-tense forms (with the T/D/IX+D voicing rule).
    "rested",
    "waited",
    "lifted",
    "guided",
    "headed",
    # More ``-tion`` / ``-sion`` words.
    "action",
    "section",
    "station",
    "fiction",
    "function",
    "junction",
    "notion",
    "option",
    "vacation",
    "donation",
    "creation",
    "direction",
    # More ``-ness`` nouns.
    "kindness",
    "softness",
    "fitness",
    "lightness",
    "freshness",
    # More ``-ful`` / ``-less`` adjectives.
    "useful",
    "painful",
    "joyful",
    "fearless",
    "endless",
    "useless",
    # More ``-est`` superlatives.
    "tallest",
    "softest",
    "kindest",
    "shortest",
    "longest",
    "coldest",
    "richest",
    # More ``-ly`` adverbs.
    "slowly",
    "loudly",
    "kindly",
    "gladly",
    "simply",
    # ``-y`` adjectives (CMU's ``IY0`` final reads as ``iy``).
    "happy",
    "funny",
    "lucky",
    "sunny",
    "windy",
    "rainy",
    "stormy",
    "cloudy",
    "sleepy",
    "fluffy",
    "lovely",
    "ugly",
    "pretty",
    "fancy",
    # Ordinal / tens number-words.
    "ten",
    "twenty",
    "thirty",
    "fifty",
    "sixty",
    "seventy",
    "eighty",
    "ninety",
    "hundred",
    "million",
    "billion",
    # ``-n't`` contractions (modal verbs + auxiliaries).
    "wouldn't",
    "shouldn't",
    "haven't",
    "hasn't",
    "doesn't",
    # Pronoun + auxiliary contractions.
    "i'm",
    "we're",
    "they're",
    "i've",
    "you've",
    "he's",
    "she's",
    "you're",
    # Common multi-syllabic standalone words.
    "computer",
    "information",
    "vegetable",
    "interesting",
    "wonderful",
    "another",
    "yesterday",
    "water",
    "paper",
    "letter",
    "summer",
    "winter",
    "season",
    "garden",
    "mountain",
    "river",
    "ocean",
    "forest",
    "weather",
    "rainbow",
    "midnight",
    "phone",
    "photo",
    # Common short-vowel standalone words.
    "go",
    "see",
    "say",
    "make",
    "take",
    "give",
    "find",
    "feel",
    "day",
    "year",
    "boy",
    "girl",
    "cat",
    "dog",
    "car",
    "chair",
    "book",
    "weak",
    "hot",
    "cold",
    "warm",
    "cool",
    "young",
    "old",
    "new",
    "fresh",
    "honest",
    "modern",
    # Common greetings and stock phrases.
    "good morning",
    "good night",
    "good evening",
    "thank you very much",
    "have a nice day",
    "welcome home",
    "see you soon",
    "what is your name",
    "where are you",
    # Prepositional phrases.
    "in the morning",
    "in the evening",
    "at the park",
    "at the store",
    "on the table",
    "under the bed",
    "next to me",
    # Imperatives and short utterances.
    "tell me more",
    "open the door",
    "turn the page",
    "ask a question",
    "make a wish",
    "have fun",
    "be careful",
    "stay safe",
    "good luck",
    "no problem",
    "i forgot",
    # SVO and short declarative sentences.
    "she runs fast",
    "the sun is bright",
    "stars in the sky",
    "trees in the park",
    "birds are singing",
    "kids are playing",
    "the food is good",
    "the music is loud",
    "books on the shelf",
    "a cup of coffee",
    "what a nice day",
    "i love music",
    "they came home",
    "she is smart",
    "it is great",
    # Additional compound words.
    "playground",
    "campfire",
    # ``-ment`` words with LTS-fallback stems: when the lex doesn't
    # have the bare-stem, the LTS-fallback path picks up the C-
    # faithful AX+N+T suffix instead of falling through to the
    # LTS-emit-of-the-whole-word (which mis-renders ``-ment`` as
    # ``M EH0 N T``).
    "fragment",
    "garment",
    # More ``-ed`` past-tense forms.
    "watched",
    "missed",
    "washed",
    "brushed",
    "picked",
    "started",
    "opened",
    "closed",
    "helped",
    "smiled",
    "called",
    "looked",
    "asked",
    "worked",
    "wanted",
    "played",
    "stayed",
    "cried",
    "moved",
    "killed",
    "filled",
    "pulled",
    "rolled",
    # Cardinal-number literal words.
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "eight",
    "nine",
    "twelve",
    # Common function words (conjunctions / prepositions / determiners).
    "but",
    "and",
    "or",
    "if",
    "with",
    "into",
    "about",
    "after",
    "before",
    "than",
    "then",
    "while",
    "what",
    "how",
    "this",
    "that",
    "these",
    "those",
    "such",
    "some",
    "any",
    "all",
    "each",
    "every",
    # Common short / medium nouns.
    "time",
    "place",
    "world",
    "life",
    "school",
    "business",
    "government",
    "week",
    "month",
    "night",
    "hour",
    "money",
    "food",
    "story",
    "page",
    "name",
    "word",
    "face",
    "hand",
    "head",
    "heart",
    "eye",
    # Auxiliary verbs.
    "do",
    "did",
    "have",
    "has",
    "will",
    "can",
    "may",
    "might",
    "must",
    "shall",
    # Common adjectives.
    "big",
    "small",
    "great",
    "good",
    "bad",
    "easy",
    "hard",
    "nice",
    "long",
    "short",
    "high",
    "low",
    "fast",
    "slow",
    "dark",
    "light",
    "clean",
    "dirty",
    "sad",
    "angry",
    "tired",
    "busy",
    "ready",
    # Multi-word phrases separated by a comma (clause-internal pause).
    "hello, world",
    "well, then",
    "yes, please",
    "no, thanks",
    "oh, no",
    "wait, what",
    # Two-word verb-particle phrases.
    "stand up",
    "sit down",
    "look at",
    "turn on",
    "come here",
    "wake up",
    "fall down",
    # Simple SVO sentences.
    "i see it",
    "we did it",
    "give me that",
    "i love you",
    "i know it",
    "i did it",
    "we know",
    # Double-letter / vowel-digraph short words.
    "look",
    "room",
    "soon",
    "moon",
    "wood",
    "feet",
    "deep",
    "sleep",
    "green",
    "tree",
    "free",
    "rain",
    "train",
    "beach",
    "road",
    "boat",
    "coat",
    "goal",
    "wait",
    "main",
    "pain",
    "snail",
    "tail",
    "dead",
    # More ``-tion`` / ``-al`` / ``-ment`` words.
    "position",
    "question",
    "social",
    "special",
    "total",
    "local",
    "general",
    "document",
    "environment",
    "moment",
    "movement",
    "argument",
    # More ``-er`` comparative adjectives.
    "better",
    "smaller",
    "bigger",
    "higher",
    "lower",
    "longer",
    "shorter",
    "older",
    "younger",
    "stronger",
    "weaker",
    "darker",
    "lighter",
    # More greeting / stock phrases.
    "thank you so much",
    "good afternoon",
    "how are you",
    # ``-ous`` / ``-able`` / ``-al`` adjective coverage.
    "anxiety",
    "various",
    "obvious",
    "generous",
    "courageous",
    "anxious",
    "valuable",
    "available",
    "possible",
    "visible",
    "unbearable",
    "pleasant",
    "abundant",
    "ancient",
    "absent",
    "racial",
    "equal",
    "annual",
    "facial",
    # ``-ic`` adjectives.
    "basic",
    "public",
    "magic",
    "plastic",
    "electric",
    "terrific",
    "tragic",
    "topic",
    "comic",
    "tropic",
    "graphic",
    "automatic",
    "ethnic",
    # Multi-syllabic ``-y`` / ``-ery`` / ``-ory`` nouns.
    "country",
    "salary",
    "library",
    "energy",
    "company",
    "industry",
    "category",
    "summary",
    "ceremony",
    "lottery",
    # More numeric / counting words.
    "dozen",
    # Days of the week.
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    # Months of the year.
    "january",
    "february",
    "march",
    "april",
    "june",
    "september",
    "october",
    "november",
    # Color words.
    "red",
    "blue",
    "yellow",
    "orange",
    "purple",
    "brown",
    "black",
    "white",
    "gray",
    "gold",
    "silver",
    # Animal names.
    "tiger",
    "bear",
    "wolf",
    "fox",
    "rabbit",
    "mouse",
    "horse",
    "cow",
    "pig",
    "sheep",
    "duck",
    "chicken",
    "fish",
    "bird",
    "snake",
    "frog",
    "ant",
    "bee",
    "deer",
    "goat",
    "eagle",
    "shark",
    "whale",
    "dolphin",
    "monkey",
    # Body-part nouns.
    "arm",
    "leg",
    "foot",
    "finger",
    "nose",
    "mouth",
    "ear",
    "hair",
    "skin",
    "bone",
    "blood",
    "brain",
    "lung",
    "elbow",
    "shoulder",
    "thumb",
    "neck",
    "back",
    "chest",
    # Family-relation nouns.
    "mother",
    "father",
    "brother",
    "sister",
    "uncle",
    "aunt",
    "child",
    "baby",
    "son",
    "daughter",
    "nephew",
    # More high-frequency verbs (those that PASS without the
    # ``)`` VPSTART marker -- mostly intransitive / stative).
    "love",
    "like",
    "want",
    "need",
    "hope",
    "wish",
    "dream",
    "try",
    "work",
    "help",
    "buy",
    "sell",
    "leave",
    "meet",
    "think",
    "speak",
    "swim",
    "jump",
    "dance",
    "sing",
    # Common adverbs.
    "here",
    "there",
    "now",
    "tomorrow",
    "late",
    "early",
    "again",
    "just",
    "only",
    "also",
    "very",
    "never",
    "often",
    "maybe",
    # Common household-object nouns.
    "table",
    "window",
    "door",
    "key",
    "pen",
    "pencil",
    "picture",
    "mirror",
    "lamp",
    "clock",
    "watch",
    "fork",
    "spoon",
    "plate",
    "bowl",
    "cup",
    "glass",
    "bottle",
    "bag",
    "box",
    # Time-related nouns.
    "century",
    "decade",
    "autumn",
    "noon",
    # Geographical / location nouns.
    "city",
    "state",
    "zone",
    "earth",
    "lake",
    "valley",
    "park",
    # Multi-word greetings / farewells.
    "hello there",
    "see you later",
    "talk to you later",
    "how have you been",
    "long time no see",
    "welcome back",
    "nice to meet you",
    # Yes/no and WH-questions (multi-word).
    "do you know",
    "can you help",
    "can you hear me",
    "do you see",
    "what is that",
    "what is this",
    "what happened",
    "where is it",
    "where is the bathroom",
    "when did you",
    "why did you",
    "which one",
    "who is that",
    "is it true",
    "is it ok",
    "who are you",
    "what time is it",
    "when will you come",
    "why not",
    "are you sure",
    "are you ready",
    "are you there",
    "are you ok",
    "is it done",
    "is it over",
    "how about you",
    # Simple SVO declarative sentences.
    "i need help",
    "i need money",
    "i need water",
    "i need food",
    "i need time",
    "the world is round",
    "the earth is blue",
    "the sky is blue",
    "the grass is green",
    "i am cold",
    "i am hot",
    "i am sad",
    "i am tired",
    "i am hungry",
    "you are right",
    "you are wrong",
    "you are kind",
    "you are great",
    "he is here",
    "she is there",
    "we are friends",
    "they are happy",
    "it is raining",
    "it is snowing",
    "it is cold",
    "it is warm",
    "it is hot",
    "it is over",
    "it is done",
    "i miss you",
    "i hate it",
    "i like it",
    "i want it",
    "i need it",
    "i hear you",
    # Imperatives + short utterances.
    "be still",
    "be patient",
    "be kind",
    "be nice",
    "stop it",
    "wait here",
    "come back",
    "go home",
    "stay here",
    "look up",
    "look down",
    "watch out",
    "wake me up",
    "hold on",
    "take it",
    "give it back",
    # Common idiomatic phrases.
    "you're welcome",
    "i'm sorry",
    "no doubt",
    "for sure",
    "at last",
    "at first",
    "by the way",
    "in fact",
    "in time",
    "at home",
    "at work",
    "in love",
    "for free",
    "in vain",
    "no way",
    "not yet",
    # Time-quantifying phrases.
    "all day",
    "all night",
    "all week",
    "all year",
    "a long time",
    "a short time",
    "for a while",
    "right now",
    "at noon",
    "at night",
    "next year",
    "last week",
    "this year",
    "next time",
    # Comma-separated 2-word phrases.
    "hello, friend",
    "wait, no",
    "well, ok",
    "ok, fine",
    "good morning, friend",
    "hello, sir",
    "yes, sir",
    "no, sir",
    "yes, of course",
    "well, well",
    "oh, yes",
    "ok, then",
    # VPSTART verbs verified to add ``)`` (base + common forms).
    "recognize",
    "advertise",
    "verify",
    "create",
    "operate",
    "demonstrate",
    "appreciate",
    "punish",
    "consider",
    "follow",
    "obtain",
    "occur",
    "perform",
    "prevent",
    "provide",
    "seek",
    "settle",
    "solve",
    "spend",
    "steal",
    "succeed",
    "suffer",
    "suggest",
    "suppose",
    "survive",
    "teach",
    "translate",
    "understand",
    "wear",
    # Negative-contraction sentences.
    "i don't know",
    "we can't go",
    "they won't help",
    "she didn't see",
    "he can't come",
    "you won't see",
    "we don't care",
    "they didn't try",
    "i won't go",
    "you can't stop",
    "she don't know",
    "he didn't say",
    # WH-question sentences.
    "what did you do",
    "where do you go",
    "how can i help",
    "why are you here",
    "where is the book",
    "what do you want",
    "where can i go",
    # Conditional ``if``-clauses.
    "if you can",
    "if you know",
    "if you want",
    "if i can",
    "if she comes",
    "if he goes",
    "if we try",
    "if they say",
    # Comparative ``than``-clauses.
    "better than that",
    "worse than ever",
    "more than enough",
    "less than two",
    "bigger than me",
    "faster than you",
    "slower than that",
    # Prepositional phrases (locative).
    "above the table",
    "across the room",
    "over the moon",
    "near the door",
    "behind the wall",
    "inside the box",
    "in front of me",
    # Single-word interjections / responses.
    "sure",
    "ok",
    "fine",
    "ouch",
    "oops",
    "yes",
    "no",
    "maybe",
    "perhaps",
    # Plural noun forms (regular -s / -es plurals).
    "books",
    "trees",
    "cars",
    "trucks",
    "boys",
    "girls",
    "schools",
    "tables",
    "chairs",
    "windows",
    "doors",
    "rooms",
    "buildings",
    # ``the`` + adjective + noun phrases.
    "the big house",
    "the red car",
    "the new book",
    "the old man",
    "the small dog",
    "the tall tree",
    "the long road",
    "the dark night",
    "the bright day",
    "the hot sun",
    "the green grass",
    "the blue sky",
    # Compound nouns (no MBOUND-marker needed).
    "sunshine",
    "moonlight",
    "daylight",
    "daytime",
    "background",
    "inside",
    # Acronyms / single-letter / -ic.
    "FAQ",
    "complete",
    "ethic",
    # ``-er`` / ``-or`` agentive nouns.
    "doctor",
    "actor",
    "monster",
    "answer",
    "matter",
    "farmer",
    "painter",
    # Musical-instrument / household nouns.
    "piano",
    "violin",
    "drum",
    "radio",
    "desk",
    # Ordinal numbers (``-st`` / ``-rd`` / ``-th``) and time-of-day.
    "first",
    "third",
    "fifth",
    "tenth",
    "afternoon",
    # 4+ word sentences (motion / location).
    "i went to the store",
    "we went to the park",
    "she went to school",
    "he went to work",
    "give me the book please",
    "tell me what you saw",
    "the dog is in the yard",
    "the cat sat on the mat",
    "we need to go home now",
    "they should leave at noon",
    "you should have told me",
    "i would like some water",
    "i went to the beach",
    "we went to the movies",
    "she went to the doctor",
    "he went to the bank",
    "the boy ran down the road",
    "the girl walked to school",
    "the bird flew over the house",
    "the fish swam in the pond",
    "we are going home",
    "they are going home",
    "she is going home",
    "he is going home",
    "i am going home",
    "we are at home",
    "they are at school",
    "the men are working",
    # Number-context phrases.
    "give me five",
    "i have three",
    "we are six",
    "two times two",
    "three and four",
    "five and six",
    "nine and ten",
    "one or two",
    "three or four",
    "two by two",
    "three by three",
    "four by four",
    # Auxiliary-modal sentences.
    "i can do it",
    "we can see it",
    "they can hear it",
    "i should go",
    "we should stop",
    "you should rest",
    "i must leave",
    "we must wait",
    "they must know",
    "we can help you",
    "you can do it",
    "she can sing",
    "he can dance",
    "they can swim",
    "i will help",
    "we will see",
    "they will come",
    "she will stay",
    "he will go",
    "i may go",
    "we may stop",
    "you may leave",
    # Coordination: word ``and`` / ``or`` joining noun-pairs.
    "yes and no",
    "this or that",
    "now or never",
    "you and me",
    "him and her",
    "rain and snow",
    "tea and coffee",
    "salt and pepper",
    "bread and butter",
    "cats and dogs",
    "boys and girls",
    "up and down",
    "in and out",
    "back and forth",
    "left and right",
    "north and south",
    "east and west",
    "black and white",
    "red and blue",
    "day and night",
    "sun and moon",
    "fish and chips",
    "milk and cookies",
    # Adjective + plural-noun phrases.
    "tired people",
    "small dogs",
    "big trees",
    "slow buses",
    "loud music",
    "soft pillows",
    "hot tea",
    "cold water",
    "warm soup",
    "fresh bread",
    "new shoes",
    "tall trees",
    "short people",
    "long roads",
    "wide rivers",
    "high mountains",
    "low ceilings",
    "bright lights",
    "dark rooms",
    "open doors",
    "closed windows",
    "empty boxes",
    "full glasses",
    # Emotional / state expressions.
    "i feel good",
    "i feel sad",
    "i feel tired",
    "you look great",
    "she looks happy",
    "i am thirsty",
    "we are happy",
    "they are tired",
    "she is happy",
    "he is sad",
    # ``-ing`` + adverb / object phrases.
    "running fast",
    "walking slowly",
    "eating lunch",
    "sleeping deeply",
    "talking loudly",
    "standing still",
    "working hard",
    "playing games",
    "reading books",
    "writing letters",
    "singing songs",
    "dancing well",
    "jumping high",
    "coming home",
    # Date / time-of-day phrases.
    "last night",
    "this morning",
    "next week",
    "this evening",
    "next month",
    "last year",
    "this week",
    "this month",
    # Past-tense / past-simple sentences.
    "i went home",
    "she came back",
    "they left early",
    "we stayed late",
    "i saw you",
    "we heard them",
    "she said yes",
    "he said no",
    "we ate lunch",
    "i drank water",
    "she sang well",
    "he ran fast",
    "they walked slowly",
    "we sat down",
    "i fell down",
    "i found it",
    "we lost it",
    # ``going to`` future phrases.
    "going to bed",
    "going to work",
    "going to school",
    "going to sleep",
    "going to eat",
    "going to play",
    # Possessive-pronoun + noun phrases.
    "my house",
    "your car",
    "his book",
    "her phone",
    "their kids",
    "the dogs bone",
    "the boys name",
    "my name",
    "your name",
    "his name",
    "her name",
    "my friend",
    "your friend",
    "his friend",
    "her friend",
    "my mother",
    "your father",
    "his sister",
    "her brother",
    "my room",
    "your room",
    "my dog",
    "your cat",
    # Place names (DECtalk's text normaliser folds case).
    "paris",
    "tokyo",
    "boston",
    "france",
    "germany",
    "china",
    "canada",
    "europe",
    "asia",
    # Short questions / commands.
    "why me",
    "why now",
    "what now",
    "what next",
    "get up",
    "lie down",
    "look out",
    "stay there",
    "turn around",
    "turn left",
    "turn right",
    # Coordinated noun pairs (body parts / foods).
    "head and shoulders",
    "hands and feet",
    "eyes and ears",
    "arms and legs",
    "coffee and tea",
    "pizza and pasta",
    "cake and cookies",
    "rice and beans",
    # ``-IFY`` verbs (LTS-fallback stem-strip path: stem + IX+F+AY).
    "modify",
    "amplify",
    "simplify",
    "testify",
    "magnify",
    "notify",
    # Spell-out acronyms with all-letters-primary-stressed (the
    # default C path, vs FBI which is special-cased in C's main dic
    # with a destressed middle letter).
    "DNA",
    "USB",
    "PDF",
    "GPS",
    "ATM",
    "DVD",
    "BBC",
    "GDP",
    "HBO",
    "HIV",
    "JFK",
    "LCD",
    "LED",
    "MBA",
    "MRI",
    "NBA",
    "NBC",
    "NFL",
    "PPE",
    "PSA",
    "RPM",
    "SEC",
    "SUV",
    "USC",
    "VIP",
    # 2-letter spell-out acronyms.
    "AC",
    "DC",
    "EU",
    "FM",
    "GM",
    "IT",
    "JS",
    "KP",
    "ML",
    "OK",
    "PR",
    "TM",
    "US",
    "VR",
    "XL",
    # Round 7: longer sentences, time/space, common phrases.
    "the boy and the girl played",
    "i have been to the store",
    "she has been working hard",
    "they have been here all day",
    "i went to the doctor yesterday",
    "we will see you tomorrow at noon",
    "the cars drove down the road",
    "i have ten cats",
    "we ate five apples",
    "she bought three books",
    "we walked for two hours",
    "i have one cat",
    "i have two dogs",
    "we ate four apples",
    "she bought six books",
    "we walked for three hours",
    "in january",
    "in february",
    "in march",
    "in april",
    "in may",
    "in june",
    "in september",
    "in october",
    "in november",
    "next monday",
    "last friday",
    "next tuesday",
    "last monday",
    "next wednesday",
    "next thursday",
    "next friday",
    "next saturday",
    "next sunday",
    "last tuesday",
    "last wednesday",
    "last thursday",
    "last saturday",
    "last sunday",
    "on monday",
    "on tuesday",
    "on wednesday",
    "on thursday",
    "on friday",
    "on saturday",
    "on sunday",
    "don't go",
    "don't stop",
    "don't run",
    "don't cry",
    "don't move",
    "don't talk",
    "don't sleep",
    "don't eat",
    "don't sit",
    "do not stop",
    "do not run",
    "do not go",
    "do not move",
    "do not talk",
    "i'm fine",
    "i'm tired",
    "i'm happy",
    "i'm sad",
    "i'm cold",
    "i'm hot",
    "i'm hungry",
    "i'm thirsty",
    "i'm ready",
    "i'm busy",
    "you're tall",
    "you're smart",
    "you're nice",
    "you're kind",
    "you're funny",
    "she's pretty",
    "she's tall",
    "she's smart",
    "she's nice",
    "he's tall",
    "he's smart",
    "he's nice",
    "he's kind",
    "what's up",
    "what's that",
    "where's the door",
    "who's there",
    "what's this",
    "where's the cat",
    "where's the dog",
    "where's the book",
    "what's wrong",
    "what's new",
    "i love coffee",
    "you love tea",
    "she loves music",
    "he loves books",
    "we love our friends",
    "i love tea",
    "i love books",
    "i love food",
    "i love water",
    "she loves coffee",
    "she loves tea",
    "he loves coffee",
    "he loves tea",
    "we love coffee",
    "they love music",
    "in the box",
    "on the chair",
    "beside the door",
    "near the window",
    "in the room",
    "on the floor",
    "under the table",
    "under the chair",
    "behind the door",
    "behind the chair",
    "near the wall",
    "beside the window",
    "i went to the store and bought milk",
    "she went home and slept",
    "i went home and slept",
    "we went home and slept",
    "he went home and slept",
    "as big as a house",
    "as small as a mouse",
    "as fast as light",
    "more than ten",
    "less than five",
    "more than five",
    "less than ten",
    "more than three",
    "as big as a cat",
    "as small as a cat",
    "the cat is sleeping",
    "the dog is barking",
    "the bird is flying",
    "the fish swims",
    "the cow eats grass",
    "the cat sleeps",
    "the dog barks",
    "the bird sings",
    "the cat is jumping",
    "the dog is running",
    "the bird is singing",
    "the cat is eating",
    "the dog is eating",
    "the cat is running",
    "it's raining",
    "it's sunny",
    "it's cloudy",
    "it's snowing",
    "the weather is nice",
    "it's cold",
    "it's hot",
    "it's warm",
    "it's windy",
    "the weather is cold",
    "the weather is hot",
    "the weather is warm",
    "i want pizza",
    "we eat dinner",
    "she drinks water",
    "the food is hot",
    "the soup is cold",
    "i want food",
    "i want water",
    "i want tea",
    "i want coffee",
    "we eat lunch",
    "she drinks tea",
    "she drinks coffee",
    "he drinks water",
    "he drinks tea",
    "the food is cold",
    "the soup is hot",
    "the coffee is hot",
    "the tea is cold",
    "the water is cold",
    "the water is hot",
    # ``-IFY`` verbs unlocked by the AH0+F+stressed-AY -> IX rule
    # (justify is the canonical case: lex AY2 triggers IX where AY0
    # forms like notify / verify keep AX).
    "justify",
    "classify",
    "horrify",
    # ``-SIFY`` verbs unlocked by the AH0+S+F+AY -> IX rule.
    "satisfy",
    # Long SVO sentences (5+ words) covering motion / location.
    "we are going to the beach",
    "they went to the store yesterday",
    "i bought a new car last week",
    "we should go to bed now",
    "the boy is reading a book",
    "the girl is playing with the dog",
    "we are going to the park",
    "they are coming to the house",
    "i went to the store yesterday",
    "she walked to the school",
    "he opened the door for me",
    "the cat is sleeping on the bed",
    "the dog is running in the yard",
    "we ate dinner at the restaurant",
    "they live in a big house",
    "she sang a song for us",
    "he played the piano for me",
    # Verb-particle phrases.
    "go on",
    "go off",
    "go in",
    "go out",
    "go up",
    "go down",
    "go back",
    "go now",
    "go ahead",
    "go inside",
    "come on",
    "come off",
    "come in",
    "come over",
    "come down",
    "come up",
    "come out",
    "come along",
    "come now",
    "get on",
    "get off",
    "get in",
    "get out",
    "get down",
    "get back",
    "get ready",
    "get going",
    "get well",
    "get over",
    "put on",
    "put off",
    "put in",
    "put out",
    "put up",
    "put down",
    "put back",
    "take on",
    "take off",
    "take out",
    "take in",
    "take up",
    "take down",
    "take over",
    "take back",
    "set up",
    "set down",
    "set off",
    "set out",
    "turn off",
    "turn down",
    "turn up",
    "turn over",
    "turn back",
    # Politeness-marker sentences.
    "please help",
    "please come",
    "please stop",
    "please wait",
    "please go",
    "please leave",
    "please answer",
    "please call",
    "please try",
    "may i help",
    "may i ask",
    "may i come in",
    "may i go",
    "may i see",
    "would you like",
    "could you please",
    "could you help",
    "could you come",
    # ``what`` / ``how`` interrogative phrases.
    "what color",
    "what time",
    "what day",
    "what kind",
    "what size",
    "what name",
    "what month",
    "what year",
    "how old",
    "how big",
    "how far",
    "how long",
    "how much",
    "how many",
    "how nice",
    "how cold",
    "how warm",
    "how fast",
    "how slow",
    "where to go",
    "what to do",
    "when to leave",
    "where to find",
    "what to say",
    "where to start",
    # ``-ed`` past-tense in 4-word sentences.
    "the cat watched the bird",
    "we walked to school",
    "she asked a question",
    "he opened the door",
    "they painted the house",
    "i washed the dishes",
    "she cleaned the kitchen",
    "we played in the park",
    "they laughed at the joke",
    "i closed the window",
    "he answered the phone",
    # Coordinated noun-pair sentences.
    "the man and the woman",
    "the boy and the dog",
    "the sun and the moon",
    "the cat and the dog",
    "the man and the boy",
    "the boy and the girl",
    "the king and the queen",
    "the mother and the father",
    # Pronoun + auxiliary expansion.
    "i can go",
    "you can go",
    "he can go",
    "she can go",
    "we can go",
    "they can go",
    "i can see",
    "you can see",
    "we can see",
    "we can do it",
    "i can help",
    "you can help",
    "we can help",
    "i can try",
    "i can wait",
    "i will go",
    "you will go",
    "she will go",
    "we will go",
    "they will go",
    "i will see",
    "i will try",
    "i will wait",
    "i will come",
    # ``more`` / ``some`` quantifier phrases.
    "give me more",
    "i want more",
    "i need more",
    "show me more",
    "give us more",
    "i need some help",
    "give me some water",
    "i want some food",
    "i need some time",
    "i want some coffee",
    "i need some money",
    "give me some time",
    "i want some tea",
    # Short comments / quality phrases.
    "good idea",
    "bad idea",
    "nice job",
    "great work",
    "good job",
    "good work",
    "nice work",
    "good day",
    "no time",
    "no place",
    "no idea",
    "no chance",
    "no one",
    # Conjunction-headed clauses.
    "but i can't",
    "and i will",
    "or you can",
    "but i will",
    "and i can",
    "but you can",
    "and they will",
    "or we can",
    # Time-of-day phrases.
    "in the afternoon",
    "at midnight",
    "at dawn",
    "at dusk",
    "in the night",
    "during the day",
    # ``have to`` modal phrases.
    "i have to go",
    "we have to wait",
    "they have to leave",
    "i have to see",
    "i have to try",
    "we have to go",
    "you have to go",
    "they have to go",
    "i have to think",
    "she has to go",
    "he has to go",
    # ``want to`` modal phrases.
    "i want to go",
    "we want to see",
    "they want to play",
    "i want to see",
    "i want to know",
    "i want to help",
    "i want to try",
    "you want to go",
    "we want to go",
    "they want to go",
    "i want to stay",
    "i want to come",
    "i want to leave",
    # ``need to`` modal phrases.
    "i need to go",
    "we need to wait",
    "she needs to leave",
    "i need to see",
    "i need to know",
    "i need to think",
    "we need to go",
    "you need to go",
    "i need to talk",
    "i need to try",
    "he needs to go",
    "they need to go",
    "i need to leave",
    "i need to stop",
    # ``yes`` / ``no`` short answers.
    "yes please",
    "yes thanks",
    "yes i can",
    "yes i did",
    "yes i am",
    "yes i will",
    "no thanks",
    "no thank you",
    # Three-word imperatives / requests.
    "look at me",
    "wait for me",
    "come with me",
    "go with me",
    "stay with me",
    "tell me why",
    "tell me how",
    "show me how",
    "show me why",
    "take it back",
    "tell me what",
    "tell me when",
    "listen to me",
    # Habitual adverbial sentences.
    "i always go",
    "i never go",
    "we sometimes go",
    "i often go",
    "i always eat",
    "i never eat",
    "i always run",
    "i never run",
    "i always win",
    "i never win",
    "i always know",
    "i never know",
    # ``do you`` interrogatives.
    "do you go",
    "do you come",
    "do you eat",
    "do you drink",
    "do you write",
    "do you speak",
    "do you sing",
    "do you run",
    "do you play",
    "do you swim",
    "do you dance",
    "do you cook",
    "do you sleep",
    "do you work",
    "do you have",
    # Speaker-stance phrases.
    "i guess",
    "i suppose",
    "i hope so",
    "i wonder",
    "i doubt it",
    "i hope not",
    # Sequential coordination / fixed expressions.
    "this and that",
    "now and then",
    "here and there",
    "more or less",
    "give or take",
    "rain or shine",
    "win or lose",
    # Past-tense activity sentences.
    "i played the piano",
    "she sang a song",
    "they cooked dinner",
    "i baked a cake",
    "i opened the door",
    "she closed the window",
    "we walked home",
    "i talked to him",
    "she laughed loud",
    # Singular-noun adjective+noun phrases.
    "a nice car",
    "a big house",
    "a small dog",
    "a long book",
    "a short story",
    "a hot day",
    "a cold night",
    "a green field",
    "a tall man",
    "a fast car",
    "a slow train",
    "a young boy",
    "a old man",
    "a wise woman",
    "a kind teacher",
    "a strong horse",
    # Self-introduction / proper-name patterns.
    "i am bob",
    "my name is bob",
    "she is mary",
    "i am john",
    "i am tom",
    "i am sam",
    "my name is sam",
    "she is jane",
    "he is dan",
    "we are tom and jane",
    "hello mary",
    "hello bob",
    "hello john",
    # Color + noun phrases.
    "the red apple",
    "the green tree",
    "the white snow",
    "the black cat",
    "the yellow sun",
    "the red rose",
    "the blue ocean",
    "the brown bear",
    "the gray wolf",
    "the pink flower",
    # Counting sequences.
    "one two three",
    "four five six",
    "ten eleven twelve",
    "two three four",
    "three four five",
    "eight nine ten",
    # Subject + ``is`` / ``are`` + state.
    "i am here",
    "we are there",
    "he is home",
    "she is busy",
    "we are tired",
    "i am ready",
    "we are done",
    "he is mad",
    "she is glad",
    "we are late",
    "they are early",
    # ``any`` quantifier phrases.
    "any time",
    "any day",
    "any place",
    "any one",
    "any thing",
    "any way",
    "any second",
    # ``every`` quantifier phrases.
    "every day",
    "every night",
    "every time",
    "every place",
    "every one",
    "every thing",
    "every week",
    "every month",
    "every year",
    "every morning",
    "every evening",
    # Number + age / quantity.
    "i am twenty",
    "she is thirty",
    "he is fifty",
    "i need ten",
    "we have five",
    "i want three",
    "give me four",
    "i see six",
    # Compound greetings.
    "hello how are you",
    "thanks you too",
    "good night sleep well",
    "good morning friend",
    "good evening sir",
    "hello my friend",
    # Descriptive sentences.
    "the snow is white",
    "the night is dark",
    "the day is long",
    # Pronoun + verb-of-perception + you.
    "i need you",
    "i see you",
    "i know you",
    "i trust you",
    "i thank you",
    "you are nice",
    "you are smart",
    "we won it",
    "we have it",
    "well done",
    "nice try",
    # ``what's`` / ``where's`` / ``who's`` apostrophe-s contractions.
    "what's up",
    "what's that",
    "where's the door",
    "where's the key",
    "who's there",
    "who's home",
    # ``time`` adverbial phrases.
    "all the time",
    "on time",
    "out of time",
    # ``is that`` question phrases.
    "is that you",
    "is that all",
    "is that right",
    "is that ok",
    # Negation phrases.
    "not quite",
    "not at all",
    # Gratitude phrases.
    "thanks a lot",
    "many thanks",
    # State sentences.
    "i am angry",
    # ``the X one`` phrases.
    "the only one",
    "the best one",
    "the next one",
    "the last one",
    "the right one",
    "the wrong one",
    "the same one",
    # Ordinal placement / time phrases.
    "first place",
    "second place",
    "third place",
    "first time",
    "second time",
    "last time",
    # ``to be`` infinitive phrases.
    "to be or not to be",
    "to be honest",
    "to be fair",
    # ``as ... as`` comparative phrases.
    "as long as",
    "as much as",
    "as soon as",
    "as fast as",
    "as far as",
    # ``a + adjective + man / girl`` phrases.
    "a smart man",
    "a kind man",
    "a brave man",
    "a strong man",
    "a kind girl",
    "a brave girl",
    "a tall girl",
    # Quantifier-pronoun phrases.
    "a little bit",
    "a lot",
    # More descriptive sentences.
    "the dog is happy",
    "the boy is sad",
    # ``i can`` + sense/perception verbs.
    "i can hear",
    "i can feel",
    "i can taste",
    "i can smell",
    "i can touch",
    # Subject + verb + the + noun.
    "we love the dog",
    "they love the cat",
    "the boys are playing",
    "the girls are dancing",
    # Round 10 corpus expansion: high-frequency vocabulary +
    # short SVO sentences across multiple categories.
    "ball",
    "bench",
    "brick",
    "broom",
    "candle",
    "comb",
    "hammer",
    "ladder",
    "ring",
    "soap",
    "bend",
    "bite",
    "blow",
    "boil",
    "break",
    "burn",
    "burst",
    "count",
    "crawl",
    "cut",
    "dig",
    "drag",
    "drop",
    "fall",
    "fight",
    "fill",
    "fix",
    "flip",
    "fly",
    "freeze",
    "grab",
    "hide",
    "hit",
    "hop",
    "hug",
    "hunt",
    "kick",
    "laugh",
    "lift",
    "listen",
    "melt",
    "mix",
    "paint",
    "pass",
    "pinch",
    "pull",
    "ride",
    "rise",
    "roll",
    "rub",
    "sail",
    "shake",
    "share",
    "shine",
    "shoot",
    "shout",
    "show",
    "shut",
    "sigh",
    "skate",
    "skip",
    "slap",
    "slide",
    "smell",
    "smile",
    "sneeze",
    "snore",
    "sob",
    "stand",
    "stare",
    "stay",
    "stir",
    "strike",
    "suck",
    "surf",
    "sweep",
    "swing",
    "talk",
    "tap",
    "taste",
    "tickle",
    "touch",
    "trick",
    "twist",
    "vote",
    "walk",
    "wash",
    "wave",
    "weep",
    "weigh",
    "whisper",
    "win",
    "wipe",
    "wonder",
    "the rain falls down",
    "the snow falls slow",
    "the leaves fall down",
    "the stars shine bright",
    "the moon glows bright",
    "the bird flies high",
    "the dog runs fast",
    "the cat sits down",
    "the fish swims fast",
    "the boy runs home",
    "the girl sings well",
    "the baby cries loud",
    "the child plays well",
    "they look happy",
    "the dog wags",
    "the bee flies",
    "the rain falls",
    "the snow falls",
    "an old book",
    "a big cat",
    "a happy boy",
    "a sad girl",
    "a big dog",
    "a red ball",
    "a blue car",
    "a tall tree",
    "a short man",
    "a long road",
    "a wide river",
    "a dark room",
    "a bright light",
    "stop and go",
    "run and jump",
    "sit and wait",
    "stand and watch",
    "look and see",
    "come and go",
    "wash and dry",
    "mix and stir",
    "sing and dance",
    "rest and play",
    "apple juice",
    "orange juice",
    "cold milk",
    "hot soup",
    "sweet cake",
    "warm tea",
    "hot coffee",
    "fresh fish",
    "white rice",
    "brown rice",
    "red apple",
    "green apple",
    "ripe banana",
    "fresh fruit",
    "for real",
    "of late",
    "at once",
    "at all",
    "by far",
    "my cat",
    "your dog",
    "her bag",
    "your house",
    "his car",
    "her car",
    "my mom",
    "my dad",
    "your mom",
    "your dad",
    "i can write",
    "i can sing",
    "i can dance",
    "i can swim",
    "i can run",
    "i can jump",
    "i can play",
    "i can talk",
    "i can walk",
    "i can cook",
    "i can drive",
    "five cats",
    "ten dogs",
    "three boys",
    "two girls",
    "many cars",
    "no toys",
    "six birds",
    "four men",
    "eight cars",
    "two hands",
    "ten fingers",
    "five toes",
    "two feet",
    "very nice",
    "very kind",
    "very smart",
    "very happy",
    "very good",
    "very bad",
    "very sad",
    "very loud",
    "very tall",
    "very small",
    "very big",
    "very old",
    "very young",
    "floor",
    "wall",
    "roof",
    "flower",
    "grass",
    "leaf",
    "sand",
    "rock",
    "hill",
    "field",
    "morning",
    "evening",
    "sunset",
    "i know him",
    "i know her",
    "i know that",
    "she sees me",
    "he sees me",
    "they see me",
    "yes sir",
    "no sir",
    "red bird",
    "blue bird",
    "black cat",
    "white dog",
    "yellow sun",
    "green grass",
    "blue sky",
    "white snow",
    "brown bear",
    "gray cat",
    "pink flower",
    "toe",
    "ankle",
    "tooth",
    "lip",
    "chin",
    "cheek",
    "tongue",
    "soft",
    "rough",
    "sharp",
    "dull",
    "thick",
    "thin",
    "wide",
    "shallow",
    "heavy",
    "empty",
    "full",
    "open",
    "wet",
    "dry",
    "rich",
    "poor",
    "whose",
    "cup of tea",
    "cup of milk",
    "loaf of bread",
    "piece of cake",
    "come home",
    "stay home",
    "leave home",
    "open up",
    "shut up",
    "my book is",
    "my dog is",
    "my cat is",
    "your bag is",
    "the sun is very bright",
    "the dog is very nice",
    "the cat is very small",
    "i love my dog",
    "i love my cat",
    "i love my mom",
    "i love my dad",
    "she loves her dog",
    "he loves his dog",
    "one cat",
    "two cats",
    "three cats",
    "four cats",
    "one dog",
    "two dogs",
    "three dogs",
    "four dogs",
    "one boy",
    "two boys",
    "one girl",
    "early morning",
    "late evening",
    "late night",
    "early afternoon",
    "i am sorry",
    "have a great day",
    "song",
    "note",
    "beat",
    "rhythm",
    "snowy",
    "sun",
    "snow",
    "cloud",
    "storm",
    "warm day",
    "cold day",
    "rainy day",
    "sunny day",
    "windy day",
    "study",
    "baby brother",
    "big sister",
    "little brother",
    "old uncle",
    "i go home",
    "i come home",
    "i sit down",
    "i stand up",
    "i wake up",
    "i lie down",
    "i look up",
    "i look down",
    "warm spring",
    "hot summer",
    "cold winter",
    "cool autumn",
    "vase",
    "mop",
    "bin",
    "rug",
    "egg",
    "ham",
    "cheese",
    "butter",
    "jam",
    "honey",
    "salt",
    "sugar",
    "tea",
    "milk",
    "juice",
    "wine",
    "beer",
    "ham and eggs",
    "cat food",
    "dog food",
    "fish food",
    "bird food",
    "cat toy",
    "dog toy",
    "kid toy",
    "school day",
    "school book",
    "very fast",
    "very slow",
    "very long",
    "very short",
    "very wet",
    "very dry",
    "very rich",
    "very poor",
    "very dark",
    "very deep",
    "he is",
    "she is",
    "they are",
    "we are",
    "you are",
    "i am",
    "he was",
    "she was",
    "they were",
    "we were",
    "you were",
    "i was",
    "i will",
    "i should",
    "i would",
    "i could",
    "i must",
    "you will",
    "you should",
    "you would",
    "you could",
    "you must",
    "starlight",
    "snowman",
    "snowflake",
    "schoolhouse",
    "classroom",
    "dancing",
    "working",
    "thinking",
    "smiling",
    "laughing",
    "who is",
    "what is",
    "where is",
    "when is",
    "why is",
    "how is",
    "who are",
    "what are",
    "where are",
    "when are",
    "who was",
    "what was",
    "where was",
    "it is dark",
    "it is light",
    "it is good",
    "it is bad",
    "it is nice",
    "it is true",
    "i do not know",
    "i do not care",
    "i do not see",
    "i do not hear",
    "fan",
    "fire",
    "ice",
    "smoke",
    "dust",
    "mud",
    "dirt",
    "soil",
    "stick",
    "stone",
    "pebble",
    "crystal",
    "puppy",
    "bunny",
    "lamb",
    "calf",
    "foal",
    "chick",
    "go to bed",
    "go to school",
    "go to work",
    "go to sleep",
    "go to play",
    "go to church",
    "go to bath",
    "i am running",
    "i am walking",
    "i am playing",
    "i am eating",
    "i am sleeping",
    "i am working",
    "i am reading",
    # More 2-word adverbial / SVO patterns.
    "always go",
    "never go",
    "dogs bark",
    "cats meow",
    "birds sing",
    "fish swim",
    "playing music",
    "speaking loudly",
    "feel good",
    "feel bad",
    "feel sad",
    "feel happy",
    "pick up",
    "drop off",
    "eating bread",
    "drinking water",
    "best wishes",
    "one hour",
    "two hours",
    "three hours",
    "many days",
    "i still wait",
    "i still think",
    "i never lose",
    "we still hope",
    "are you here",
    "is it home",
    "do you have it",
    "did you see it",
    "have you seen",
    "has she done",
    "had they been",
    "in the kitchen",
    "in the living room",
    "the cat meows",
    "the cup is empty",
    "the box is full",
    "the door is open",
    "the room is dark",
    "the road is long",
    "is this it",
    "is this true",
    "but i can",
    "can you go",
    "can you stay",
    "can you wait",
    "wait a second",
    "old book",
    "new book",
    "big book",
    # Future / past-habitual constructions.
    "i am going to go",
    "we are going to see",
    "they are going to come",
    "i'm going to bed",
    "we're going home",
    "i used to go",
    "we used to go",
    "they used to live",
    # Common verb + noun phrases.
    "win the game",
    "lose the bet",
    "make a friend",
    "find the answer",
    "lose the keys",
    "find the keys",
    "the song i sang",
    # Polite request phrases.
    "could you tell me",
    "could you show me",
    "could you give me",
    "would you mind",
    "would you like to",
    # Existential ``there + be``.
    "there is a dog",
    "there are dogs",
    "there was a cat",
    "there were boys",
    # Habituals + temporal.
    "we go every day",
    "we go on monday",
    # Ditransitive imperatives.
    "give me the book",
    "tell me the truth",
    # ``what a`` / ``such a`` exclamatives.
    "such a nice day",
    "what a day",
    "what a nice",
    # Directional prepositional phrases.
    "to the store",
    "to the park",
    "to the moon",
    # Verb + gerund.
    "stop running",
    "start walking",
    "keep going",
    "stop talking",
    # Imperative + manner adverb.
    "go quickly",
    "go slowly",
    "come closer",
    # Possessive + linking verb.
    "my friend is",
    "your dog is",
    "his cat is",
    # Coordinated yes/no.
    "yes or no",
    # ``X for you`` predicate.
    "good for you",
    "bad for you",
    "right for you",
    # Two-modifier noun phrases.
    "a good little book",
    # Emphatic / cleft "it is X" patterns.
    "it is i",
    "it is you",
    "it is me",
    "it was i",
    # Modal-existential ``there + modal + be``.
    "there will be",
    "there might be",
    "there must be",
    # Quantifier-headed phrases.
    "all the people",
    "all the days",
    "none of them",
    "one of them",
    "two of them",
    # Tag-question phrases.
    "is not it",
    "was not it",
    # WH-cleft ``what i X``.
    "what i want",
    "what i need",
    "what i know",
    "what i did",
    # Pronoun + adverb of degree + verb.
    "i hardly see",
    # ``if you X`` conditionals.
    "if you go",
    "if you come",
    "if you stay",
    # ``have/had/will been`` auxiliary chains.
    "i have been",
    "we have been",
    "they have been",
    "i had been",
    "we had been",
    "they had been",
    "i will be",
    "we will be",
    "they will be",
    # Long-range progressive sentences.
    "the rain is falling",
    "the moon is rising",
    # ``very very`` intensification.
    "very very nice",
    "very very bad",
    # Action verb + object.
    "i kick the ball",
    "i throw the ball",
    "i catch the ball",
    "i hit the ball",
    # ``X or Y`` interrogative-pair.
    "what or why",
    "where or when",
    # Pronoun + transitive + pronoun.
    "she sees us",
    "he sees us",
    # ``the X`` natural-phenomenon noun phrases.
    "the fire",
    "the ice",
    "the sea",
    "the air",
    "the sky",
    # Number + duration noun.
    "five years",
    "ten years",
    "twenty years",
    # ``A and B`` color pairs.
    "red and white",
    "blue and white",
    "green and white",
    # More short-vowel verbs.
    "begin",
    "end",
    "start",
    # Abstract nouns.
    "peace",
    "joy",
    "honor",
    "wisdom",
    # ``you can X`` / ``i will X`` modal phrases.
    "you can stay",
    "you can wait",
    "i will stay",
    "i will leave",
    # Longer sentence.
    "love is in the air",
    # Imperative + object pronoun phrases.
    "open it",
    "write it",
    "say it",
    "show it",
    "throw it",
    "catch it",
    "hit it",
    # ``i feel + adjective`` mood phrases.
    "i feel cold",
    "i feel hot",
    "i feel sick",
    # More single-word adjectives / nouns.
    "kind",
    "wise",
    "stupid",
    "lazy",
    "loud",
    "office",
    "kitchen",
    "bathroom",
    # ``more / less than`` comparisons.
    "more than that",
    "less than this",
    # ``i am X that`` complement clauses.
    "i am happy that",
    "we are sad that",
    # Possessive (apostrophe-less) noun phrases.
    "the boys book",
    "the girls bag",
    # Reflexive ``by myself`` family.
    "by myself",
    "by yourself",
    "by himself",
    "by herself",
    # Auxiliary chain ``have/had been``.
    "have been here",
    "had been there",
    # Misc WH-phrases.
    "how come",
    "what for",
    # ``the day/air is X`` weather.
    "the day is sunny",
    "the day is cloudy",
    "the air is cold",
    # Tech / object noun-pairs.
    "computer mouse",
    "computer screen",
    "computer keyboard",
    "board game",
    "card game",
    # ``X by X`` idiomatic.
    "step by step",
    "day by day",
    "year after year",
    # ``this/that is the X`` superlatives.
    "this is the best",
    "that is the worst",
    "this is the same",
    "that is different",
    # ``in spite of`` etc.
    "in spite of",
    # Verb + at/for + pronoun.
    "smile at me",
    "smile for me",
    "wave at me",
    # Polite request phrases.
    "may i please",
    "could i please",
    "would you mind if",
    # ``-ing + a + noun`` phrases.
    "watching a movie",
    "reading a book",
    # ``what is X`` queries.
    "what is left",
    "what is next",
    "where to end",
    # Possessive predicate ``this is mine``.
    "this is mine",
    "this is yours",
    "this is ours",
    # Comparison ``the same as``.
    "the same as",
    # ``by myself i X``.
    "by myself i can",
    "by myself i will",
    # ``tea time`` / ``coffee break``.
    "tea time",
    "coffee break",
    # Multi-room phrases.
    "dining room",
    "living room",
    "guest room",
    # Proper-name + ``and`` pairs.
    "bob and mary",
    "mary and bob",
    # Time-of-day phrases.
    "early in the morning",
    "late at night",
    # Storyteller openings.
    "long long ago",
    "once upon a time",
    # ``do you`` interrogatives (more).
    "do you want",
    "do you need",
    "do you like",
    "do you love",
    "do you hate",
    "do you understand",
    "do you care",
    # ``you will X`` future-prediction.
    "you will know",
    "you will see",
    "you will find",
    "you will love",
    "you will hear",
    # ``won't`` contractions.
    "i won't see",
    "i won't hear",
    "we won't see",
    # ``you need to X``.
    "you need to know",
    "you need to see",
    "you need to try",
    # ``i think X``.
    "i think it is",
    "i think you are",
    "i think we are",
    "i think they are",
    # ``X will do it``.
    "we will do it",
    "i will do it",
    "they will do it",
    # More short verbs.
    "play",
    "draw",
    "cook",
    # ``X go / come / eat / sleep`` (we/they).
    "we go",
    "we come",
    "we eat",
    "we sleep",
    "they go",
    "they come",
    "they eat",
    # Past-tense subject+verb.
    "the dog ran",
    "the bird sang",
    "i saw it",
    "we saw it",
    "they saw it",
    # Conditional ``if X``.
    "if i go",
    "if we leave",
    # ``hello + name``.
    "hello sam",
    "hello tom",
    "hello dan",
    # Number-repeat.
    "ten ten",
    "five five",
    # Money phrase.
    "give me a dollar",
    # ``a X story`` adjective+noun.
    "a happy story",
    "a sad story",
    "a funny story",
    "a long story",
    # State.
    "we are alone",
    # ``we / they need to think``.
    "we need to think",
    "they need to think",
    "i want to think",
    # ``X time`` compound nouns.
    "play time",
    "lunch time",
    "dinner time",
    "story time",
    "bed time",
    # Two-adjective + noun.
    "the big red ball",
    "a small blue car",
    # Idiom + nursery.
    "give me a hand",
    "row your boat",
    "twinkle twinkle",
    # Day-of-week + holiday greetings.
    "happy monday",
    "happy tuesday",
    "happy friday",
    "merry christmas",
    "happy easter",
    # Hedge / opinion phrases.
    "in my opinion",
    "if you ask me",
    "as far as i know",
    "as a matter of fact",
    # ``X what / else``.
    "now what",
    "so what",
    "what else",
    "who else",
    # Strong adverbs.
    "definitely yes",
    # Conditional clauses.
    "if all goes well",
    "if it works",
    # ``make a / take a / have a`` light verb constructions.
    "make a list",
    "take a break",
    "have a seat",
    # Cohortative ``let me X``.
    "let me see",
    "let me try",
    "let me think",
    "let me know",
    # Occupation nouns.
    "lawyer",
    "nurse",
    "manager",
    "officer",
    "soldier",
    # Address phrases.
    "my dear friend",
    "dear sir",
    # Money amounts.
    "five dollars",
    "ten dollars",
    "twenty cents",
    "five cents",
    # Distance.
    "five miles",
    "ten miles",
    "one mile",
    # Time-amount phrases.
    "an hour",
    "two hours later",
    # ``thats X`` (no apostrophe variant).
    "thats mine",
    "thats yours",
    "thats his",
    # ``I/we/they am/are moving``.
    "i am moving",
    "we are moving",
    "they are moving",
    # ``i am eating X``.
    "i am eating lunch",
    "i am eating dinner",
    # ``lots of X``.
    "lots of fun",
    "lots of love",
    "lots of luck",
    # ``X is/was fun``.
    "this is fun",
    "that is fun",
    "that was fun",
    "this was fun",
    # Subject nouns.
    "math",
    "english",
    "art",
    # ``i am brave``.
    "i am brave",
    # ``the best / worst ever``.
    "the best ever",
    "the worst ever",
    # ``tell me about`` / ``teach me how``.
    "tell me about",
    "teach me how",
    # 3rd-person singular present (-s suffix).
    "she sings",
    "he sings",
    "she dances",
    "he dances",
    "she plays",
    "he plays",
    "she works",
    "he works",
    "she runs",
    "he runs",
    "she walks",
    "he walks",
    # Negative quantifier + noun.
    "no rain",
    "no snow",
    "no sun",
    "no food",
    "no water",
    "no money",
    # Number + noun (more).
    "five eggs",
    "six eggs",
    "ten eggs",
    "ten cats",
    # ``we can X`` modal phrases.
    "we can run",
    "we can jump",
    # Progressive aspect.
    "she is dancing",
    "he is singing",
    "they are running",
    "we are reading",
    "i am studying",
    # Imperative + ``me``.
    "watch me",
    "help me",
    "tell me",
    "show me",
    "follow me",
    # ``we/they are here / were there``.
    "we are here",
    "they are here",
    "i was there",
    "we were there",
    "they were there",
    # ``i/we made X``.
    "i made coffee",
    "i made dinner",
    "i made lunch",
    "we made plans",
    "we made friends",
    # Idiomatic ``X or Y``.
    "thick or thin",
    "do or die",
    # ``the X`` (positional).
    "the end",
    "the middle",
    # ``X it again``.
    "say it again",
    "do it again",
    "try it again",
    # Reflexive ``i V myself``.
    "i washed myself",
    "i hurt myself",
    # ``the day is bright``.
    "the day is bright",
    # ``is it color``.
    "is it red",
    "is it blue",
    "is it green",
    # Round 11 corpus expansion: SVO sentences, math facts, travel,
    # cooking, weather, sports, family relations, multi-word
    # noun/adjective phrases, partitive ``of`` phrases,
    # number words (hundreds/thousands/millions), ``the X`` noun
    # phrases, ``very + adj`` adverb pairs, ``let us X`` cohortative,
    # animal sounds, locative ``in / on the X``, body parts.
    "the boys ran to the park",
    "the girls played in the field",
    "my brother is taller than yours",
    "your sister is younger than mine",
    "the cat slept on the mat",
    "the boy ran down the street",
    "the girl walked to the store",
    "the woman cooked the dinner",
    "the baby slept in the crib",
    "we drove to the mountains",
    "they walked to the beach",
    "she sang a beautiful song",
    "he played the piano",
    "we watched the movie",
    "they listened to the music",
    "the rain fell on the roof",
    "the snow covered the ground",
    "the sun shone on the lake",
    "five times five is twenty five",
    "a triangle has three sides",
    "a square has four sides",
    "a circle is round",
    "the earth is round",
    "the sun is a star",
    "water is wet",
    "fire is hot",
    "ice is cold",
    "snow is white",
    "grass is green",
    "blood is red",
    "gold is yellow",
    "ten times ten is one hundred",
    "two times three is six",
    "we went to the airport",
    "they flew to paris",
    "i drove to the beach",
    "we walked to the park",
    "she took a train",
    "we rented a car",
    "she missed the flight",
    "i baked a pie",
    "we cooked the dinner",
    "i ate an apple",
    "we drank some milk",
    "he made some coffee",
    "she boiled the eggs",
    "i made a sandwich",
    "she baked a cake",
    "we ate some bread",
    "it might rain",
    "it will be sunny",
    "the snow is melting",
    "it is raining outside",
    "it is snowing outside",
    "the clouds are dark",
    "they played football",
    "she ran the race",
    "he won the game",
    "we watched the game",
    "she helped her mother",
    "he called his father",
    "she loves her sister",
    "he misses his brother",
    "we kissed our aunt",
    "they thanked their uncle",
    "magazine",
    "newspaper",
    "sofa",
    "ceiling",
    "blanket",
    "pillow",
    "accept",
    "agree",
    "demand",
    "forget",
    "fresh apples",
    "sweet oranges",
    "dark shadows",
    "warm milk",
    "cold beer",
    "what do you think",
    "i agree with you",
    "you make a point",
    "that is a fact",
    "i do not agree",
    "you are correct",
    "i am wrong",
    "that is right",
    "that is wrong",
    "i am not sure",
    "i wish i knew",
    "a sunny morning",
    "a rainy afternoon",
    "a cold winter",
    "a hot summer day",
    "a snowy night",
    "a warm evening",
    "a cool morning",
    "a beautiful day",
    "a long week",
    "a short month",
    "very pretty",
    "very ugly",
    "very stupid",
    "very clever",
    "very simple",
    "very easy",
    "very hard",
    "very angry",
    "we ate pizza yesterday",
    "she sang a song last night",
    "they came back yesterday",
    "a long beautiful road",
    "a short funny story",
    "a small old house",
    "a big new car",
    "a tall thin man",
    "a short fat woman",
    "cup of coffee",
    "glass of water",
    "bowl of soup",
    "bag of chips",
    "box of crackers",
    "bottle of wine",
    "pound of meat",
    "two thousand",
    "five hundred",
    "one thousand",
    "many years",
    "several hours",
    "three years",
    "ten days",
    "twenty days",
    "fifty years",
    "one hundred",
    "two hundred",
    "ten thousand",
    "one million",
    "the rain",
    "the snow",
    "the sun",
    "the moon",
    "the star",
    "the cloud",
    "the tree",
    "the flower",
    "the leaf",
    "the river",
    "the ocean",
    "the lake",
    "the mountain",
    "the valley",
    "the hill",
    "the road",
    "the bridge",
    "the city",
    "the town",
    "you can try it",
    "we can win",
    "she will sing",
    "he will play",
    "i must go",
    "you must stay",
    "we should leave",
    "they would help",
    "the field",
    "the farm",
    "the garden",
    "the park",
    "the beach",
    "the forest",
    "the harbor",
    "the lighthouse",
    "the castle",
    "the church",
    "the temple",
    "the library",
    "the school",
    "the office",
    "the factory",
    "the restaurant",
    "the cafe",
    "the store",
    "the shop",
    "the bank",
    "the post office",
    "the airport",
    "very strong",
    "very weak",
    "very dumb",
    "very thin",
    "very fat",
    "very wide",
    "very shallow",
    "very brave",
    "the snake is a reptile",
    "the bird is a vertebrate",
    "the bee is an insect",
    "the shark is a fish",
    "a cube has six faces",
    "cows moo",
    "horses neigh",
    "sheep bleat",
    "ducks quack",
    "frogs croak",
    "three thousand",
    "four thousand",
    "six thousand",
    "eight thousand",
    "nine thousand",
    "three hundred",
    "four hundred",
    "six hundred",
    "eight hundred",
    "nine hundred",
    "two million",
    "three million",
    "four million",
    "five million",
    "ten million",
    "knife and fork",
    "cup and saucer",
    "table and chair",
    "lock and key",
    "rod and reel",
    "fresh oranges",
    "ripe pears",
    "fresh peaches",
    "ripe plums",
    "sweet grapes",
    "sour lemons",
    "at sunset",
    "during the week",
    "during the month",
    "yesterday was monday",
    "tomorrow is friday",
    "pound of beef",
    "pound of butter",
    "ounce of gold",
    "pint of milk",
    "quart of milk",
    "slice of bread",
    "slice of cake",
    "slice of pie",
    "in the bathroom",
    "in the garden",
    "in the park",
    "in the office",
    "in the school",
    "in the city",
    "in the country",
    "in the woods",
    "in the house",
    "on the wall",
    "on the bed",
    "on the road",
    "on the bridge",
    "on the beach",
    "on the mountain",
    "i am sleepy",
    "i am busy",
    "she is sad",
    "she is angry",
    "he is tall",
    "he is short",
    "he is young",
    "he is old",
    "they are busy",
    "where do you live",
    "how old are you",
    "what day is it",
    "where is the store",
    "where is the park",
    "let us go",
    "let us play",
    "let us sing",
    "let us dance",
    "let us eat",
    "let us drink",
    "let us write",
    "let us learn",
    "let us think",
    "i went to bed",
    "i went to school",
    "i went to work",
    "she went home",
    "he went home",
    "we went home",
    "they went home",
    "i want milk",
    "i want bread",
    "i need rest",
    "raincoat",
    "boots",
    "scarf",
    "gloves",
    "hat",
    "shirt",
    "pants",
    "shoes",
    "socks",
    "belt",
    "tie",
    "dress",
    "skirt",
    "eyes",
    "ears",
    "hands",
    "arms",
    "legs",
    "shoulders",
    "knees",
    "elbows",
    "fingers",
    "toes",
    # Rounds 12-13 corpus expansion: 349 high-frequency vocabulary +
    # sentence patterns (verbs, idiomatic phrases, ``the X`` noun
    # phrases, ``i X`` past-tense, common ``X`` compound nouns,
    # SVO sentences, questions, conditionals, modal sequences,
    # quantifiers, relative clauses, this/that copulas, possessive
    # ``i X it`` patterns, money phrases, imperative+object,
    # greeting+name, time references, negative contractions,
    # compound nouns, profession copulas, negative ability).
    "breathe",
    "climb",
    "peer",
    "pierce",
    "plant",
    "plead",
    "plug",
    "print",
    "prove",
    "quench",
    "race",
    "raise",
    "reach",
    "rear",
    "reap",
    "rest",
    "rinse",
    "rip",
    "rob",
    "roast",
    "run",
    "save",
    "scare",
    "scatter",
    "scoop",
    "score",
    "scribble",
    "seal",
    "seat",
    "seem",
    "seize",
    "send",
    "serve",
    "shade",
    "shape",
    "shave",
    "shear",
    "shed",
    "sheen",
    "shell",
    "shift",
    "shoo",
    "shop",
    "shrink",
    "sift",
    "sign",
    "sink",
    "sip",
    "sit",
    "ski",
    "slip",
    "snap",
    "sniff",
    "soak",
    "sort",
    "speed",
    "spell",
    "spill",
    "spin",
    "split",
    "spoil",
    "spot",
    "spray",
    "spread",
    "sprout",
    "squeeze",
    "stab",
    "stack",
    "stain",
    "stamp",
    "starve",
    "steam",
    "steer",
    "stem",
    "step",
    "stew",
    "sting",
    "stoke",
    "stomp",
    "stop",
    "store",
    "strain",
    "stride",
    "string",
    "strip",
    "stuff",
    "sum",
    "supply",
    "surrender",
    "surround",
    "sway",
    "swear",
    "swell",
    "swoop",
    "tack",
    "tackle",
    "tag",
    "tame",
    "tan",
    "tempt",
    "tend",
    "test",
    "thank",
    "thaw",
    "thrust",
    "tilt",
    "tip",
    "tire",
    "toast",
    "tow",
    "trace",
    "trade",
    "trap",
    "travel",
    "treat",
    "tremble",
    "trim",
    "trip",
    "trot",
    "trouble",
    "trust",
    "tug",
    "tumble",
    "turn",
    "the day after tomorrow",
    "the day before yesterday",
    "all over again",
    "over and over",
    "as good as new",
    "as bad as ever",
    "the best of both worlds",
    "easy come easy go",
    "no pain no gain",
    "live and learn",
    "wait and see",
    "first and last",
    "sooner or later",
    "by and large",
    "loud and clear",
    "safe and sound",
    "high school",
    "elementary school",
    "middle school",
    "old school",
    "new school",
    "home town",
    "home owner",
    "fresh start",
    "fresh air",
    "no comment",
    "next door",
    "last month",
    "tell me a story",
    "sing me a song",
    "show me the way",
    "give me a chance",
    "lend me your ear",
    "take me home",
    "bring me water",
    "pass the salt",
    "open the window",
    "turn off the light",
    "turn on the radio",
    "the song",
    "the singer",
    "the band",
    "the music",
    "the violin",
    "the piano",
    "the drum",
    "the trumpet",
    "the flute",
    "play the song",
    "play the piano",
    "sing a song",
    "go north",
    "go south",
    "go east",
    "go west",
    "go left",
    "go right",
    "look around",
    "go there",
    "two cups",
    "three bowls",
    "four birds",
    "five fish",
    "six trees",
    "eight chairs",
    "nine tables",
    "ten books",
    "one apple",
    "two pears",
    "three plums",
    "i taught",
    "i bought",
    "i sold",
    "i kept",
    "i lost",
    "i found",
    "i ran",
    "i walked",
    "i sat",
    "i fell",
    "i slept",
    "i ate",
    "i drank",
    "i sang",
    "i danced",
    "i played",
    "i worked",
    "i studied",
    "i wrote",
    "i drew",
    "i painted",
    "i made",
    "i built",
    "i broke",
    "i cooked",
    "i cleaned",
    "sweet dreams",
    "catch you later",
    "have a good day",
    "take care",
    "be safe",
    "stay strong",
    "the stars",
    "the storm",
    "the grass",
    "sweet tea",
    "black coffee",
    "white sugar",
    "the cat",
    "the dog",
    "the bird",
    "the fish",
    "the cow",
    "the pig",
    "the sheep",
    "the tiger",
    "the bear",
    "the wolf",
    "the fox",
    "the rabbit",
    "the mouse",
    "the rat",
    "the boy walked down the street",
    "the girl ran across the yard",
    "we drove to the new restaurant",
    "i played in the big park",
    "the man walked into the room",
    "the woman sat on the bench",
    "the cat ran across the road",
    "the bird flew over the trees",
    "the boy threw the ball",
    "the man drove the car",
    "the dog chased the cat",
    "she drove to the office",
    "do you like coffee",
    "do you like tea",
    "do you have any money",
    "do you have any time",
    "if i were you",
    "if you were me",
    "if it were possible",
    "if i had time",
    "if you had money",
    "i should have known",
    "we could have gone",
    "they would have come",
    "i would have stayed",
    "many of them",
    "some of them",
    "most of them",
    "all of them",
    "the boy who came",
    "the girl that left",
    "the man we met",
    "the woman i saw",
    "the friend i met",
    "the song i heard",
    "the movie i saw",
    "the house we bought",
    "i wake up early",
    "i go to sleep",
    "we eat at noon",
    "that is bad",
    "this is great",
    "this is fine",
    "that is fine",
    "this is nice",
    "that is nice",
    "this is hard",
    "this is easy",
    "this is true",
    "i love it",
    "i have it",
    "i made it",
    "i lost it",
    "i bought it",
    "i broke it",
    "i heard it",
    "i felt it",
    "i have money",
    "i need a dollar",
    "tell me a joke",
    "tell me a secret",
    "show me the way",
    "give me a chance",
    "give me a moment",
    "send me a letter",
    "good morning mary",
    "good morning john",
    "good morning sir",
    "good evening mary",
    "this very moment",
    "right this moment",
    "at this moment",
    "in a moment",
    "for a moment",
    "in an hour",
    "for an hour",
    "i don't care",
    "i don't mind",
    "i don't see",
    "i don't hear",
    "i don't think",
    "you don't know",
    "we don't have",
    "they don't see",
    "ice cream",
    "hot dog",
    "milk shake",
    "coffee cup",
    "tea cup",
    "soup bowl",
    "dinner plate",
    "kitchen sink",
    "she is a teacher",
    "he is a doctor",
    "she is a nurse",
    "i don't know why",
    "i can't see",
    "i can't hear",
    "i can't go",
    "i can't come",
    "i can't stay",
    "i can't wait",
    "i can't tell",
    # Smaller batch of round 14-15 prompts (kept conservative to
    # stay under the FD ceiling for the parametrised parity test).
    "a beach",
    "a bike",
    "a boat",
    "a breeze",
    "a cake",
    "a car",
    "a class",
    "a cliff",
    "a coat",
    "a course",
    "a dress",
    "a forest",
    "a hamster",
    "a hat",
    "a hill",
    "a lake",
    "a meeting",
    "a mountain",
    "a piece of cake",
    "a pizza",
    "a plane",
    "a puppy",
    "a rabbit",
    "a river",
    "a sandwich",
    "a ship",
    "a shirt",
    "a storm",
    "a student",
    "a teacher",
    "a tornado",
    "a truck",
    "a valley",
    "act quickly",
    "all day long",
    "all night long",
    "all of it",
    "all of my friends",
    "all of the day",
    "all of the time",
    "all of us",
    "all of you",
    "all the way",
    "all week long",
    "all year long",
    "allow",
    "anger",
    "ankles",
    "another one",
    "apple",
    "assist",
    "attempt",
    "attic",
    "back door",
    "back porch",
    "back yard",
    "bad day",
    "bagel",
    "banana",
    "basement",
    "bathroom door",
    "beaches",
    "bean",
    "bedroom door",
    "beef",
    "beg",
    "berry",
    "big cat",
    "blame",
    "blindness",
    "blink",
    "blue and gold",
    "blue and silver",
    "boats",
    "boiled egg",
    "borrow",
    "bright blue",
    "bright red",
    "brightness",
    "brown and tan",
    "brush",
    "build",
    "burger",
    "bury",
    "butterfly",
    "by chance",
    "by now",
    "by then",
    "cake",
    "catch",
    "celery",
    "cherry",
    "cleverness",
    "cloudy day",
    "coats",
    "cocoa",
    "coffee",
    "cold and dark",
    "cookie",
    "cool day",
    # Round 14-15 batch 2: more vocabulary + sentence patterns.
    "coolness",
    "courses",
    "dark beer",
    "dark blue",
    "dark red",
    "deafness",
    "death",
    "deck",
    "deep blue",
    "deep sorrow",
    "den",
    "do it now",
    "do it quickly",
    "doctors",
    "dresses",
    "drink quickly",
    "dryness",
    "eat slowly",
    "eighth one",
    "endings",
    "entry",
    "fairly slow",
    "fall back",
    "fear",
    "feed the dog",
    "feels good",
    "feels nice",
    "fields",
    "fifth one",
    "fifty to one hundred",
    "first day",
    "first one",
    "five thousand",
    "five to fifteen",
    "five to ten",
    "fog",
    "for a day",
    "for a week",
    "for then",
    "four to eight",
    "foyer",
    "fresh cheese",
    "fresh juice",
    "fresh meat",
    "front door",
    "front porch",
    "front yard",
    "fruit",
    "garage",
    "garlic",
    "give in",
    "give up",
    "go along",
    "go around",
    "go over",
    "good afternoon to you",
    "good evening to you",
    "good morning to you",
    "goose",
    "grape",
    "great fear",
    "great joy",
    "green and gold",
    "green tea",
    "hail",
    "hamsters",
    "happy and free",
    "harbor",
    "hardly",
    "hardness",
    "hate",
    "hats",
    "he builds",
    "he catches",
    "he is writing",
    "he played a game with the boys",
    "he sees himself",
    "he was tall",
    "heads",
    "hold back",
    "hold off",
    "hold out",
    "hold up",
    "hot and sunny",
    "hot cocoa",
    "hot day",
    "how is it",
    "i accept",
    "i admit",
    "i allow",
    "i am old",
    "i am speaking",
    "i am thinking",
    "i am writing",
    "i appreciate",
    "i assist",
    "i blame",
    "i borrow",
    "i brush",
    "i build",
    # Round 14-15 batch 3: remaining prompts (cached oracle lifts FD ceiling).
    "i catch",
    "i dream",
    "i feel",
    "i forget",
    "i guess so",
    "i have a pet",
    "i help myself",
    "i hope",
    "i know",
    "i see myself",
    "i sleep",
    "i understand",
    "i wake",
    "i was happy",
    "i was young",
    "i wish",
    "iced tea",
    "in a day",
    "in a month",
    "in a week",
    "in a year",
    "in the long run",
    "in the nick of time",
    "in the same boat",
    "is it cold",
    "is it hot",
    "is it snowing",
    "it feels bad",
    "it feels good",
    "it feels nice",
    "it feels warm",
    "it is cloudy",
    "it is misty",
    "it is snowy",
    "it is stormy",
    "it is sunny",
    "it is windy",
    "it looks bad",
    "it looks good",
    "it looks nice",
    "it smells bad",
    "it smells fresh",
    "it smells nice",
    "it smells sweet",
    "it sounds bad",
    "it sounds good",
    "it tastes bitter",
    "it tastes great",
    "it tastes sour",
    "it tastes sweet",
    "it was cloudy",
    "it was cold",
    "it was hot",
    "it was raining",
    "it was snowing",
    "it was sunny",
    "it was windy",
    "kind and loving",
    "kitchen table",
    "lakes",
    "last night i slept",
    "last one",
    "last year we moved",
    "laugh hard",
    "lemonade",
    "light blue",
    "light red",
    "listen up",
    "living room couch",
    "look at her",
    "look at him",
    "look at the lake",
    "look at the moon",
    "look at the mountain",
    "look at the river",
    "look at the sea",
    "look at the sky",
    "look at the stars",
    "look at the sun",
    "look at the trees",
    "look at them",
    "look at us",
    "look closely",
    "look down on",
    "look out for",
    "look up to",
    "looks beautiful",
    "looks good",
    "looks nice",
    "many of us",
    "many of you",
    "meat",
    "meetings",
    "mist",
    "most of us",
    "most of you",
    "moth",
    "mountains",
    "my afternoon",
    "my arms",
    "my cake",
    "my coat",
    "my ears",
    "my evening",
    "my eyes",
    "my feet",
    "my fingers",
    "my foot",
    "my hand",
    "my hands",
    "my hat",
    "my head",
    "my knee",
    "my legs",
    "my morning",
    "my neck",
    "my night",
    "my pet",
    "my pizza",
    "my sandwich",
    "my shirt",
    "my shoes",
    "my socks",
    "my soup",
    "my toes",
    "neatness",
    "necks",
    "next one",
    "next week we travel",
    "nice day",
    "ninth one",
    "none of us",
    "none of you",
    "noodle",
    "nurses",
    "old and tired",
    "on the same page",
    "one and only",
    "one at a time",
    "one bad apple",
    "one billion",
    "one by one",
    "one good turn",
    "one last thing",
    "one more time",
    "one of a kind",
    "one to eight",
    "one to fifteen",
    "one to five",
    "one to nine",
    "one to six",
    "one to ten",
    "one to twelve",
    "one to twenty",
    "onion",
    "out of the blue",
    "pale blue",
    "pale red",
    "pale yellow",
    "pantry",
    "pasta",
    "peach",
    "pear",
    "pepper",
    "pet the cat",
    "pie",
    "pizza",
    "plain",
    "play fairly",
    "plum",
    "porch",
    "pork",
    "potato",
    "pretty fast",
    "punch",
    "quite nice",
    "rather good",
    "red and gold",
    "red and silver",
    "rest time",
    "rice",
    "rich and famous",
    "richness",
    "ripe tomato",
    "rivers",
    "rocks",
    "rooster",
    "run quickly",
    "sad and alone",
    "sadly",
    "sandwich",
    "say it clearly",
    "say it loudly",
    "say it softly",
    "school night",
    "second day",
    "second one",
    "settle down",
    "she builds",
    "she catches",
    "she forgot the keys",
    "she is reading",
    "she sees herself",
    "she was short",
    "ships",
    "shirts",
    "sickness",
    "side door",
    "side yard",
    "sing loudly",
    "sing softly",
    "sit still",
    "six to twelve",
    "sixth one",
    "sleep deeply",
    "slow down",
    "slow turtle",
    "small dog",
    "smells good",
    "smells nice",
    "smile widely",
    "snack time",
    "snowy day",
    "so big",
    "so short",
    "so small",
    "so tall",
    "some of us",
    "some of you",
    "sorrow",
    "sorry about",
    "sorry about that",
    "sounds good",
    "sounds great",
    "sounds nice",
    "soup",
    "sour lemon",
    "speak clearly",
    "speak up",
    "stand still",
    "step back",
    "stormy day",
    "students",
    "study hard",
    "stunning",
    "sweet apple",
    "sweetness",
    "take after",
    "talk loudly",
    "tastes good",
    "tasty",
    "teachers",
    "ten to fifty",
    "ten to twenty",
    "tenderness",
    "tenth one",
    "thank you for",
    "the afternoon",
    "the ankle",
    "the baby slept all night",
    "the big picture",
    "the bike",
    "the black night",
    "the boat",
    "the boy and the girl played in the park",
    "the breeze",
    "the cake",
    "the canyon",
    "the car",
    "the cat and the dog slept",
    "the cat sat on the chair",
    "the city hall",
    "the class",
    "the cliff",
    "the closing",
    "the clouds",
    "the course",
    "the cow moos",
    "the death",
    "the duck quacks",
    "the early bird",
    "the elbow",
    "the ending",
    "the evening",
    "the fear",
    "the fire station",
    "the first day",
    "the fish swam in the river",
    "the fog",
    "the frost",
    "the girl walked to the park",
    "the hail",
    "the hamster",
    "the hat",
    "the hate",
    "the head",
    "the heel",
    "the hope",
    "the joy",
    "the knee",
    "the last day",
    "the last straw",
    "the life",
    "the love",
    "the man walked to the store",
    "the meeting",
    "the mist",
    "the morning",
    "the neck",
    "the next day",
    "the night",
    "the notebook",
    "the opening",
    "the other day",
    "the pants",
    "the parking lot",
    "the peace",
    "the pizza",
    "the plain",
    "the plane",
    "the pond",
    "the puppy",
    "the rain fell on the city",
    "the reading",
    "the same day",
    "the sandwich",
    "the second day",
    "the ship",
    "the shirt",
    "the shoes",
    "the shore",
    "the shoulder",
    "the sleet",
    "the socks",
    "the soup",
    "the speaking",
    "the stream",
    "the student",
    "the study",
    "the sun rose in the east",
    "the swimming pool",
    "the teacher",
    "the thinking",
    "the third day",
    "the toe",
    "the tornado",
    "the train",
    "the train station",
    "the truck",
    "the van",
    "the war",
    "the whole nine yards",
    "the wisdom",
    "the wood",
    "the wrist",
    "the writing",
    "theater",
    "they accept",
    "they agree",
    "they allow",
    "they are thinking",
    "they build",
    "they catch",
    "they help themselves",
    "they know",
    "they lost",
    "they understand",
    "they were here",
    "thickness",
    "think clearly",
    "third day",
    "third one",
    "this afternoon we played",
    "this morning i woke",
    "three to six",
    "tomato",
    "tomorrow he leaves",
    "tomorrow we will go",
    "trains",
    "true love",
    "turkey",
    "turtle",
    "twenty to thirty",
    "two to four",
    "two to ten",
    "under the weather",
    "valleys",
    "vans",
    "very cold",
    "very hot",
    "very new",
    "very warm",
    "walk slowly",
    "walk the dog",
    "war",
    "warm and friendly",
    "watch closely",
    "we accept",
    "we allow",
    "we are big",
    "we are ready",
    "we are speaking",
    "we are writing",
    "we blame",
    "we brush",
    "we build",
    "we catch",
    "we forgot the names",
    "we help ourselves",
    "we tried",
    "we understand",
    "we were ready",
    "we were small",
    "we won",
    "weakness",
    "wet and rainy",
    "wetness",
    "what is it",
    "when is it",
    "where is that",
    "where is this",
    "whisper softly",
    "who is it",
    "who is this",
    "why is it",
    "wildness",
    "work hard",
    "work time",
    "write clearly",
    "write neatly",
    "yellow and gold",
    "yesterday i went home",
    "yogurt",
    "you help yourself",
    "you see yourself",
    "you tried",
    # Quick batch 10: holidays, music, food, possessives, etc.
    "new year's day",
    "valentine's day",
    "rock and roll",
    "country music",
    "chocolate cake",
    "apple pie",
    "data",
    "info",
    "code",
    "file",
    "two days",
    "three weeks",
    "four months",
    "ten hours",
    "what are we doing",
    "where are we going",
    "my book",
    "my pen",
    "my pencil",
    "my paper",
    "my desk",
    "my chair",
    "my table",
    "i love this song",
    "i hate that movie",
    "i see the moon",
    "i hear the music",
    "you are clever",
    "you are wise",
    "he loves her",
    "she loves him",
    "they love us",
    "thirty thirty",
    "forty forty",
    "fifty fifty",
    "tomorrow at noon",
    "in paris",
    "in tokyo",
    "in boston",
    "in new york",
    "he plays football",
    "she plays piano",
    "they play music",
    "who knows",
    "who cares",
    "oh that's nice",
    "the friendly stranger",
    "i need to eat now",
    "we need to go now",
    "they need to leave now",
)


__all__ = ["CORPUS"]
