"""Shared bit-parity corpus used by the binary-WAV test and tooling.

The same list is consumed by:

- ``tests/parity/test_binary_wav_parity.py`` -- asserts each prompt
  renders to a byte-identical WAV vs the shipped DECtalk binary.
- ``scripts/diagnose_audio.py`` (with ``--bit-parity-corpus``) --
  materialises the corpus into ``docs/audio_samples/`` for human
  inspection and committed-into-repo audio comparison artefacts.

Edits to this tuple affect both paths.
"""

from __future__ import annotations

CORPUS: tuple[str, ...] = (
    # Original baseline corpus.
    "hello world",
    "the quick brown fox",
    "she sells sea shells",
    "one two three four five",
    "supercalifragilisticexpialidocious",
    "[:rate 250] testing one two three",
    "DECtalk version 6.2.0",
    "this is a test, with a comma, and a period.",
    # Numbers and decimal.
    "the answer is 42",
    "3 point 14",
    "one hundred and one dalmatians",
    "1234567890",
    # Punctuation variants.
    "hello! how are you?",
    "wait... what just happened?",
    "yes; no; maybe.",
    # Inline-command rate.
    "[:rate 100] slow",
    "[:rate 400] fast speech",
    # Inline-command voice presets -- exercise the 9 canonical voices.
    "[:nb] betty speaking",
    "[:nh] harry speaking",
    "[:nf] frank speaking",
    "[:nd] dennis speaking",
    "[:nk] kit the kid",
    "[:nu] ursula speaking",
    "[:nr] rita rough",
    "[:nw] wendy whispery",
    # Spell-out cases (short all-caps).
    "FBI",
    "NASA",
    "USA",
    "MIT",
    # Common English phonotactics.
    "judge thought rhythms",
    "knight light right",
    # Mixed punctuation with abbreviations.
    "Dr. Smith said hello.",
    # Long-ish utterance.
    "the rain in spain falls mainly on the plain",
    # Syllabic-L (US_EL) coverage: word-final L after consonant.
    "apple table bottle",
    "a little bottle",
    "middle of the road",
    # Syllabic-N (US_EN) coverage: word-final N after consonant.
    "button sudden reason",
    "broken eaten",
    # -ING reduction (AH0/IH0 -> ix before NG).
    "morning evening running meeting",
    # WH-question intonation: ``?`` -> ``.`` token when the sentence
    # contains a wh- word; yes/no questions keep the ``?`` marker.
    "how?",
    "what time is it?",
    # Function-word destressing of ``to`` (SBOUND + PPSTART + T + UH).
    "to bed",
    "walk to the store",
    # Function-word destressing of ``for`` (SBOUND + PPSTART + F + ER).
    "for now",
    "for ever",
    # Root-internal S after R must NOT voice to Z (``course`` / ``horse``
    # stay with final S; inflectional ``cars`` / ``sells`` voice to Z).
    "of course",
    "the horse",
    "cars and trucks",
    # First-verb stress (``are``/``had``/``is``/``was``/``were``/``will``)
    # at sentence start gets secondary stress; mid-sentence stays unstressed.
    "is it raining",
    "this is good",
    "it was good",
    # Stem-stripping plurals: lookup falls back to the singular stem
    # (``seconds`` -> ``second``), with syllabic-N / voicing applied.
    "two seconds",
    "three reasons",
    "five days",
    "two trees",
    # ``-er`` agentive / comparative suffix: stem stripping.
    "later",
    "faster",
    # ``-ed`` past-tense suffix: stem stripping + voicing/epenthesis rule
    # (T after voiceless, IX+D after T/D, D after voiced).
    "walked",
    "talked",
    "needed",
    "loved",
    "liked",
    # ``-ing`` gerund / present-participle suffix: stem stripping + IX NG.
    "walking",
    "talking",
    "jumping",
    "running",
    # ``'s`` contraction (``that's`` = ``that is``): strip the apostrophe
    # and append S (voicing handled by the encoder).
    "that's",
    "it's",
    "what's",
    "there's",
    # ``-ness`` noun-forming suffix: stem + ``N IX S``.
    "darkness",
    "sadness",
    "happiness",
    # ``-ful`` / ``-less`` adjective suffixes.
    "helpful",
    "helpless",
    "careless",
    # ``-ment`` noun-forming suffix.
    "payment",
    "shipment",
    "statement",
    # ``-tion`` / ``-sion`` (AH0+N -> IX+N after SH/ZH/CH/JH/R).
    "nation",
    "mission",
    # ``-est`` superlative suffix.
    "smallest",
    "oldest",
    "fastest",
    "biggest",
    # Y -> I morphological alternation in plurals (``cities`` -> ``city``).
    "cities",
    "babies",
    "cherries",
    # Y -> I in -ed past tense (``studied`` -> ``study``).
    "studied",
    "tried",
    # Mono-syllabic AH0+S (``us``) keeps AX; multi-syllabic uses IX.
    "us",
    # ``-n't`` contractions: N becomes syllabic-EN before the trailing T.
    "didn't",
    "couldn't",
    # AH0 + F + L word-final (the ``-iful`` connector): AH0 -> IX.
    "beautiful",
    # -OUS suffix: AH0+S -> AX after M/V/F/etc. obstruents; -> IX after
    # L/N/R sonorants.
    "famous",
    "nervous",
    "jealous",
    # ``-it`` suffix: AH0+T word-final -> IX+T when the stressed vowel is
    # a short monophthong (visit / limit / edit / audit). Diphthong-stressed
    # private / climate keep AX+T.
    "visit",
    "limit",
    "private",
    # Post-stress AH0+N+T after R -> IX (``parent`` -> ``p ' eyr ixn t``).
    "parent",
    # N -> NG velar assimilation before K / G (``pink`` -> ``p ' ihnxk``).
    "pink",
    "tank",
    # -ness with LTS-fallback stem (firm / odd not in lexicon).
    "firmness",
    "oddness",
    # Longer phrasal corpus -- exercises mid-sentence first-verb destressing,
    # function-word reductions, and inflectional morphology together.
    "a good day",
    "three nice gifts",
    "the cat is happy",
    "the dogs ran",
    "you are welcome",
    "an apple tree",
    # Hyphenated compounds: emit ``#`` syllable-break instead of word break.
    "forty",
    "forty-two",
    "twenty-one",
    "self-taught",
    # Teen words: ``*`` MBOUND marker before T+IY+N. Literal forms use
    # secondary stress on IY; digit-expanded forms use primary stress.
    "fourteen",
    "fifteen",
    "sixteen",
    "eighteen",
    "15",
    "18",
    # Sibilant-final plurals: IX+Z epenthesis (classes / horses / roses).
    "classes",
    "horses",
    "kisses",
    "foxes",
    # AH0+Z after sibilant reads as IX+Z (sibilant 3rd-person sg -es).
    "fixes",
    "fishes",
    "watches",
    # M-in-cluster + AH0+S -> IX (``christmas`` -- SM cluster, IX).
    # M-after-vowel + AH0+S -> AX (``famous`` -- EY+M, AX).
    "christmas",
    # ``-ly`` adverb suffix: consonant-final stem + L + IY0.
    "friendly",
    "softly",
    "badly",
    "quickly",
    # ``-it`` short-vowel rule now covers IY / UW tense monophthongs too.
    "spirit",
    # Number / teen edge cases.
    "eleven",
    "thirteen",
    "13",
    # -tion / -sion suffix: stem-strip + SH + AH0 + N.
    "pension",
    "mansion",
    "tension",
    # Syllabic-N before word-final D (``thousand`` -> ``th' awz end``).
    "thousand",
    "second",
    # More multi-word phrasal coverage.
    "a good idea",
    "three small dogs",
    "open the windows",
    "two cats and three dogs",
    # Multi-syllabic AH0+Z (always) -> IX; monosyllabic (was) -> AX.
    "always",
    # Multi-syllabic AH0+K / IH0+K word-final -> IX (the -IC suffix).
    "music",
    "classic",
    "panic",
    # Multi-syllabic AH0+D word-final -> IX (-ID suffix), gated to
    # exclude liquid clusters (``hundred axd``) and vowel prev
    # (``period iyaxd``). Also fires for the plural ``methods``.
    "method",
    "methods",
    # AH0+V (-ive) / AH0+SH (-ish) / AH0+P (-up) / AH0+F (-iff) /
    # IH0 variants of same.
    "active",
    "passive",
    "creative",
    "finish",
    "radish",
    "syrup",
    "gossip",
    "mastiff",
    "cousin",
    "robin",
    # SH/ZH/CH/JH + AH0 + S -> IX (``conscious``, ``precious`` if in lex).
    "conscious",
    # More multi-word phrasal coverage with combined rules.
    "the lights are on",
    "random things",
    "fast cars",
    "busy bees",
    "social media",
    # AH0+N+T word-final -> IX regardless of preceding consonant.
    "silent",
    "distant",
    "patient",
    # VPSTART verb expansion: many common verbs now get the ``)`` marker.
    "we should go",
    "they will see",
    "you can ask",
    "thank you",
    "i think so",
    "see you tomorrow",
    "i want some",
    "we know better",
    "they sing songs",
    "she put it down",
    # More sentences with VPSTART verbs.
    "asked a question",
    "wanted to know",
    "told the truth",
    "thinking about",
    # -ENT / -ANT words: T+AH0+N+T / K+AH0+N+T / L+AH0+N+T -> IX.
    "constant",
    "talent",
    "vacant",
    # Possessive 's after sibilant -> IX+Z (judge's, fox's, horse's).
    "judge's",
    "fox's",
    "horse's",
    # -ORY / -ERY / -ARY: ER0+IY0 reads as ``rriy`` syllabic-R.
    "factory",
    "history",
    "mystery",
    "battery",
    # MBOUND ``*`` from per-entry dictionary marker (compound morphology).
    "house",
    "birthday",
    "notebook",
    "lighthouse",
    "old house",
    "happy birthday",
    # More VPSTART verb prompts.
    "i can hear you",
    "we live here",
    # AM as a sentence-internal verb gets the ``)`` marker.
    "i am happy",
    # MADE (past of MAKE) is form-classed as a verb in C's main dic.
    "made",
    # Compound words whose C dictionary entry carries an internal
    # ``*`` MBOUND marker. Post-MBOUND vowels stay unreduced (compare
    # ``everything`` -- C emits ``thihnx`` not ``thixnx``).
    "everything",
    "everyone",
    "anywhere",
    "sometimes",
    # Onset-cluster coverage (str-/spl-/scr-/spr-/thr-/bl-/br-).
    "strong",
    "street",
    "splash",
    "screen",
    "spring",
    "throw",
    "through",
    "bright",
    "bread",
    # AW / OY diphthong coverage.
    "town",
    "down",
    "south",
    "sound",
    "voice",
    "choice",
    "noise",
    "coin",
    # Silent-letter onsets (kn-/wr-) and -ough/-ought spellings.
    "knife",
    "knee",
    "write",
    "wrong",
    "would",
    "could",
    "should",
    "though",
    "tough",
    "enough",
    "cough",
    # WH-question words (single-word utterances; the ``?`` question
    # marker handling is exercised via "how?" / "what time is it?").
    "who",
    "where",
    "when",
    "why",
    "which",
    # ``-er`` agentive nouns: stem-strip + ``rr`` emit.
    "teacher",
    "singer",
    "winner",
    "runner",
    "driver",
    "player",
    "reader",
    # Sibilant-final plurals (IX+Z epenthesis).
    "bushes",
    "buses",
    "boxes",
    "dishes",
    "pages",
    "places",
    "faces",
    # More ``-ing`` gerunds.
    "swimming",
    "reading",
    "writing",
    "playing",
    "singing",
    "cooking",
    "sleeping",
    "eating",
    "drinking",
    "feeling",
    "looking",
    "moving",
    "going",
    # More ``-ed`` past-tense forms (with the T/D/IX+D voicing rule).
    "rested",
    "waited",
    "lifted",
    "guided",
    "headed",
    # More ``-tion`` / ``-sion`` words.
    "action",
    "section",
    "station",
    "fiction",
    "function",
    "junction",
    "notion",
    "option",
    "vacation",
    "donation",
    "creation",
    "direction",
    # More ``-ness`` nouns.
    "kindness",
    "softness",
    "fitness",
    "lightness",
    "freshness",
    # More ``-ful`` / ``-less`` adjectives.
    "useful",
    "painful",
    "joyful",
    "fearless",
    "endless",
    "useless",
    # More ``-est`` superlatives.
    "tallest",
    "softest",
    "kindest",
    "shortest",
    "longest",
    "coldest",
    "richest",
    # More ``-ly`` adverbs.
    "slowly",
    "loudly",
    "kindly",
    "gladly",
    "simply",
    # ``-y`` adjectives (CMU's ``IY0`` final reads as ``iy``).
    "happy",
    "funny",
    "lucky",
    "sunny",
    "windy",
    "rainy",
    "stormy",
    "cloudy",
    "sleepy",
    "fluffy",
    "lovely",
    "ugly",
    "pretty",
    "fancy",
    # Ordinal / tens number-words.
    "ten",
    "twenty",
    "thirty",
    "fifty",
    "sixty",
    "seventy",
    "eighty",
    "ninety",
    "hundred",
    "million",
    "billion",
    # ``-n't`` contractions (modal verbs + auxiliaries).
    "wouldn't",
    "shouldn't",
    "haven't",
    "hasn't",
    "doesn't",
    # Pronoun + auxiliary contractions.
    "i'm",
    "we're",
    "they're",
    "i've",
    "you've",
    "he's",
    "she's",
    "you're",
    # Common multi-syllabic standalone words.
    "computer",
    "information",
    "vegetable",
    "interesting",
    "wonderful",
    "another",
    "yesterday",
    "water",
    "paper",
    "letter",
    "summer",
    "winter",
    "season",
    "garden",
    "mountain",
    "river",
    "ocean",
    "forest",
    "weather",
    "rainbow",
    "midnight",
    "phone",
    "photo",
    # Common short-vowel standalone words.
    "go",
    "see",
    "say",
    "make",
    "take",
    "give",
    "find",
    "feel",
    "day",
    "year",
    "boy",
    "girl",
    "cat",
    "dog",
    "car",
    "chair",
    "book",
    "weak",
    "hot",
    "cold",
    "warm",
    "cool",
    "young",
    "old",
    "new",
    "fresh",
    "honest",
    "modern",
    # Common greetings and stock phrases.
    "good morning",
    "good night",
    "good evening",
    "thank you very much",
    "have a nice day",
    "welcome home",
    "see you soon",
    "what is your name",
    "where are you",
    # Prepositional phrases.
    "in the morning",
    "in the evening",
    "at the park",
    "at the store",
    "on the table",
    "under the bed",
    "next to me",
    # Imperatives and short utterances.
    "tell me more",
    "open the door",
    "turn the page",
    "ask a question",
    "make a wish",
    "have fun",
    "be careful",
    "stay safe",
    "good luck",
    "no problem",
    "i forgot",
    # SVO and short declarative sentences.
    "she runs fast",
    "the sun is bright",
    "stars in the sky",
    "trees in the park",
    "birds are singing",
    "kids are playing",
    "the food is good",
    "the music is loud",
    "books on the shelf",
    "a cup of coffee",
    "what a nice day",
    "i love music",
    "they came home",
    "she is smart",
    "it is great",
    # Additional compound words.
    "playground",
    "campfire",
    # ``-ment`` words with LTS-fallback stems: when the lex doesn't
    # have the bare-stem, the LTS-fallback path picks up the C-
    # faithful AX+N+T suffix instead of falling through to the
    # LTS-emit-of-the-whole-word (which mis-renders ``-ment`` as
    # ``M EH0 N T``).
    "fragment",
    "garment",
    # More ``-ed`` past-tense forms.
    "watched",
    "missed",
    "washed",
    "brushed",
    "picked",
    "started",
    "opened",
    "closed",
    "helped",
    "smiled",
    "called",
    "looked",
    "asked",
    "worked",
    "wanted",
    "played",
    "stayed",
    "cried",
    "moved",
    "killed",
    "filled",
    "pulled",
    "rolled",
    # Cardinal-number literal words.
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "eight",
    "nine",
    "twelve",
    # Common function words (conjunctions / prepositions / determiners).
    "but",
    "and",
    "or",
    "if",
    "with",
    "into",
    "about",
    "after",
    "before",
    "than",
    "then",
    "while",
    "what",
    "how",
    "this",
    "that",
    "these",
    "those",
    "such",
    "some",
    "any",
    "all",
    "each",
    "every",
    # Common short / medium nouns.
    "time",
    "place",
    "world",
    "life",
    "school",
    "business",
    "government",
    "week",
    "month",
    "night",
    "hour",
    "money",
    "food",
    "story",
    "page",
    "name",
    "word",
    "face",
    "hand",
    "head",
    "heart",
    "eye",
    # Auxiliary verbs.
    "do",
    "did",
    "have",
    "has",
    "will",
    "can",
    "may",
    "might",
    "must",
    "shall",
    # Common adjectives.
    "big",
    "small",
    "great",
    "good",
    "bad",
    "easy",
    "hard",
    "nice",
    "long",
    "short",
    "high",
    "low",
    "fast",
    "slow",
    "dark",
    "light",
    "clean",
    "dirty",
    "sad",
    "angry",
    "tired",
    "busy",
    "ready",
    # Multi-word phrases separated by a comma (clause-internal pause).
    "hello, world",
    "well, then",
    "yes, please",
    "no, thanks",
    "oh, no",
    "wait, what",
    # Two-word verb-particle phrases.
    "stand up",
    "sit down",
    "look at",
    "turn on",
    "come here",
    "wake up",
    "fall down",
    # Simple SVO sentences.
    "i see it",
    "we did it",
    "give me that",
    "i love you",
    "i know it",
    "i did it",
    "we know",
    # Double-letter / vowel-digraph short words.
    "look",
    "room",
    "soon",
    "moon",
    "wood",
    "feet",
    "deep",
    "sleep",
    "green",
    "tree",
    "free",
    "rain",
    "train",
    "beach",
    "road",
    "boat",
    "coat",
    "goal",
    "wait",
    "main",
    "pain",
    "snail",
    "tail",
    "dead",
    # More ``-tion`` / ``-al`` / ``-ment`` words.
    "position",
    "question",
    "social",
    "special",
    "total",
    "local",
    "general",
    "document",
    "environment",
    "moment",
    "movement",
    "argument",
    # More ``-er`` comparative adjectives.
    "better",
    "smaller",
    "bigger",
    "higher",
    "lower",
    "longer",
    "shorter",
    "older",
    "younger",
    "stronger",
    "weaker",
    "darker",
    "lighter",
    # More greeting / stock phrases.
    "thank you so much",
    "good afternoon",
    "how are you",
    # ``-ous`` / ``-able`` / ``-al`` adjective coverage.
    "anxiety",
    "various",
    "obvious",
    "generous",
    "courageous",
    "anxious",
    "valuable",
    "available",
    "possible",
    "visible",
    "unbearable",
    "pleasant",
    "abundant",
    "ancient",
    "absent",
    "racial",
    "equal",
    "annual",
    "facial",
    # ``-ic`` adjectives.
    "basic",
    "public",
    "magic",
    "plastic",
    "electric",
    "terrific",
    "tragic",
    "topic",
    "comic",
    "tropic",
    "graphic",
    "automatic",
    "ethnic",
    # Multi-syllabic ``-y`` / ``-ery`` / ``-ory`` nouns.
    "country",
    "salary",
    "library",
    "energy",
    "company",
    "industry",
    "category",
    "summary",
    "ceremony",
    "lottery",
    # More numeric / counting words.
    "dozen",
    # Days of the week.
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    # Months of the year.
    "january",
    "february",
    "march",
    "april",
    "june",
    "september",
    "october",
    "november",
    # Color words.
    "red",
    "blue",
    "yellow",
    "orange",
    "purple",
    "brown",
    "black",
    "white",
    "gray",
    "gold",
    "silver",
    # Animal names.
    "tiger",
    "bear",
    "wolf",
    "fox",
    "rabbit",
    "mouse",
    "horse",
    "cow",
    "pig",
    "sheep",
    "duck",
    "chicken",
    "fish",
    "bird",
    "snake",
    "frog",
    "ant",
    "bee",
    "deer",
    "goat",
    "eagle",
    "shark",
    "whale",
    "dolphin",
    "monkey",
    # Body-part nouns.
    "arm",
    "leg",
    "foot",
    "finger",
    "nose",
    "mouth",
    "ear",
    "hair",
    "skin",
    "bone",
    "blood",
    "brain",
    "lung",
    "elbow",
    "shoulder",
    "thumb",
    "neck",
    "back",
    "chest",
    # Family-relation nouns.
    "mother",
    "father",
    "brother",
    "sister",
    "uncle",
    "aunt",
    "child",
    "baby",
    "son",
    "daughter",
    "nephew",
    # More high-frequency verbs (those that PASS without the
    # ``)`` VPSTART marker -- mostly intransitive / stative).
    "love",
    "like",
    "want",
    "need",
    "hope",
    "wish",
    "dream",
    "try",
    "work",
    "help",
    "buy",
    "sell",
    "leave",
    "meet",
    "think",
    "speak",
    "swim",
    "jump",
    "dance",
    "sing",
    # Common adverbs.
    "here",
    "there",
    "now",
    "tomorrow",
    "late",
    "early",
    "again",
    "just",
    "only",
    "also",
    "very",
    "never",
    "often",
    "maybe",
    # Common household-object nouns.
    "table",
    "window",
    "door",
    "key",
    "pen",
    "pencil",
    "picture",
    "mirror",
    "lamp",
    "clock",
    "watch",
    "fork",
    "spoon",
    "plate",
    "bowl",
    "cup",
    "glass",
    "bottle",
    "bag",
    "box",
    # Time-related nouns.
    "century",
    "decade",
    "autumn",
    "noon",
    # Geographical / location nouns.
    "city",
    "state",
    "zone",
    "earth",
    "lake",
    "valley",
    "park",
    # Multi-word greetings / farewells.
    "hello there",
    "see you later",
    "talk to you later",
    "how have you been",
    "long time no see",
    "welcome back",
    "nice to meet you",
    # Yes/no and WH-questions (multi-word).
    "do you know",
    "can you help",
    "can you hear me",
    "do you see",
    "what is that",
    "what is this",
    "what happened",
    "where is it",
    "where is the bathroom",
    "when did you",
    "why did you",
    "which one",
    "who is that",
    "is it true",
    "is it ok",
    "who are you",
    "what time is it",
    "when will you come",
    "why not",
    "are you sure",
    "are you ready",
    "are you there",
    "are you ok",
    "is it done",
    "is it over",
    "how about you",
    # Simple SVO declarative sentences.
    "i need help",
    "i need money",
    "i need water",
    "i need food",
    "i need time",
    "the world is round",
    "the earth is blue",
    "the sky is blue",
    "the grass is green",
    "i am cold",
    "i am hot",
    "i am sad",
    "i am tired",
    "i am hungry",
    "you are right",
    "you are wrong",
    "you are kind",
    "you are great",
    "he is here",
    "she is there",
    "we are friends",
    "they are happy",
    "it is raining",
    "it is snowing",
    "it is cold",
    "it is warm",
    "it is hot",
    "it is over",
    "it is done",
    "i miss you",
    "i hate it",
    "i like it",
    "i want it",
    "i need it",
    "i hear you",
    # Imperatives + short utterances.
    "be still",
    "be patient",
    "be kind",
    "be nice",
    "stop it",
    "wait here",
    "come back",
    "go home",
    "stay here",
    "look up",
    "look down",
    "watch out",
    "wake me up",
    "hold on",
    "take it",
    "give it back",
    # Common idiomatic phrases.
    "you're welcome",
    "i'm sorry",
    "no doubt",
    "for sure",
    "at last",
    "at first",
    "by the way",
    "in fact",
    "in time",
    "at home",
    "at work",
    "in love",
    "for free",
    "in vain",
    "no way",
    "not yet",
    # Time-quantifying phrases.
    "all day",
    "all night",
    "all week",
    "all year",
    "a long time",
    "a short time",
    "for a while",
    "right now",
    "at noon",
    "at night",
    "next year",
    "last week",
    "this year",
    "next time",
    # Comma-separated 2-word phrases.
    "hello, friend",
    "wait, no",
    "well, ok",
    "ok, fine",
    "good morning, friend",
    "hello, sir",
    "yes, sir",
    "no, sir",
    "yes, of course",
    "well, well",
    "oh, yes",
    "ok, then",
    # VPSTART verbs verified to add ``)`` (base + common forms).
    "recognize",
    "advertise",
    "verify",
    "create",
    "operate",
    "demonstrate",
    "appreciate",
    "punish",
    "consider",
    "follow",
    "obtain",
    "occur",
    "perform",
    "prevent",
    "provide",
    "seek",
    "settle",
    "solve",
    "spend",
    "steal",
    "succeed",
    "suffer",
    "suggest",
    "suppose",
    "survive",
    "teach",
    "translate",
    "understand",
    "wear",
    # Negative-contraction sentences.
    "i don't know",
    "we can't go",
    "they won't help",
    "she didn't see",
    "he can't come",
    "you won't see",
    "we don't care",
    "they didn't try",
    "i won't go",
    "you can't stop",
    "she don't know",
    "he didn't say",
    # WH-question sentences.
    "what did you do",
    "where do you go",
    "how can i help",
    "why are you here",
    "where is the book",
    "what do you want",
    "where can i go",
    # Conditional ``if``-clauses.
    "if you can",
    "if you know",
    "if you want",
    "if i can",
    "if she comes",
    "if he goes",
    "if we try",
    "if they say",
    # Comparative ``than``-clauses.
    "better than that",
    "worse than ever",
    "more than enough",
    "less than two",
    "bigger than me",
    "faster than you",
    "slower than that",
    # Prepositional phrases (locative).
    "above the table",
    "across the room",
    "over the moon",
    "near the door",
    "behind the wall",
    "inside the box",
    "in front of me",
    # Single-word interjections / responses.
    "sure",
    "ok",
    "fine",
    "ouch",
    "oops",
    "yes",
    "no",
    "maybe",
    "perhaps",
    # Plural noun forms (regular -s / -es plurals).
    "books",
    "trees",
    "cars",
    "trucks",
    "boys",
    "girls",
    "schools",
    "tables",
    "chairs",
    "windows",
    "doors",
    "rooms",
    "buildings",
    # ``the`` + adjective + noun phrases.
    "the big house",
    "the red car",
    "the new book",
    "the old man",
    "the small dog",
    "the tall tree",
    "the long road",
    "the dark night",
    "the bright day",
    "the hot sun",
    "the green grass",
    "the blue sky",
    # Compound nouns (no MBOUND-marker needed).
    "sunshine",
    "moonlight",
    "daylight",
    "daytime",
    "background",
    "inside",
    # Acronyms / single-letter / -ic.
    "FAQ",
    "complete",
    "ethic",
    # ``-er`` / ``-or`` agentive nouns.
    "doctor",
    "actor",
    "monster",
    "answer",
    "matter",
    "farmer",
    "painter",
    # Musical-instrument / household nouns.
    "piano",
    "violin",
    "drum",
    "radio",
    "desk",
    # Ordinal numbers (``-st`` / ``-rd`` / ``-th``) and time-of-day.
    "first",
    "third",
    "fifth",
    "tenth",
    "afternoon",
    # 4+ word sentences (motion / location).
    "i went to the store",
    "we went to the park",
    "she went to school",
    "he went to work",
    "give me the book please",
    "tell me what you saw",
    "the dog is in the yard",
    "the cat sat on the mat",
    "we need to go home now",
    "they should leave at noon",
    "you should have told me",
    "i would like some water",
    "i went to the beach",
    "we went to the movies",
    "she went to the doctor",
    "he went to the bank",
    "the boy ran down the road",
    "the girl walked to school",
    "the bird flew over the house",
    "the fish swam in the pond",
    "we are going home",
    "they are going home",
    "she is going home",
    "he is going home",
    "i am going home",
    "we are at home",
    "they are at school",
    "the men are working",
    # Number-context phrases.
    "give me five",
    "i have three",
    "we are six",
    "two times two",
    "three and four",
    "five and six",
    "nine and ten",
    "one or two",
    "three or four",
    "two by two",
    "three by three",
    "four by four",
    # Auxiliary-modal sentences.
    "i can do it",
    "we can see it",
    "they can hear it",
    "i should go",
    "we should stop",
    "you should rest",
    "i must leave",
    "we must wait",
    "they must know",
    "we can help you",
    "you can do it",
    "she can sing",
    "he can dance",
    "they can swim",
    "i will help",
    "we will see",
    "they will come",
    "she will stay",
    "he will go",
    "i may go",
    "we may stop",
    "you may leave",
    # Coordination: word ``and`` / ``or`` joining noun-pairs.
    "yes and no",
    "this or that",
    "now or never",
    "you and me",
    "him and her",
    "rain and snow",
    "tea and coffee",
    "salt and pepper",
    "bread and butter",
    "cats and dogs",
    "boys and girls",
    "up and down",
    "in and out",
    "back and forth",
    "left and right",
    "north and south",
    "east and west",
    "black and white",
    "red and blue",
    "day and night",
    "sun and moon",
    "fish and chips",
    "milk and cookies",
    # Adjective + plural-noun phrases.
    "tired people",
    "small dogs",
    "big trees",
    "slow buses",
    "loud music",
    "soft pillows",
    "hot tea",
    "cold water",
    "warm soup",
    "fresh bread",
    "new shoes",
    "tall trees",
    "short people",
    "long roads",
    "wide rivers",
    "high mountains",
    "low ceilings",
    "bright lights",
    "dark rooms",
    "open doors",
    "closed windows",
    "empty boxes",
    "full glasses",
    # Emotional / state expressions.
    "i feel good",
    "i feel sad",
    "i feel tired",
    "you look great",
    "she looks happy",
    "i am thirsty",
    "we are happy",
    "they are tired",
    "she is happy",
    "he is sad",
    # ``-ing`` + adverb / object phrases.
    "running fast",
    "walking slowly",
    "eating lunch",
    "sleeping deeply",
    "talking loudly",
    "standing still",
    "working hard",
    "playing games",
    "reading books",
    "writing letters",
    "singing songs",
    "dancing well",
    "jumping high",
    "coming home",
    # Date / time-of-day phrases.
    "last night",
    "this morning",
    "next week",
    "this evening",
    "next month",
    "last year",
    "this week",
    "this month",
    # Past-tense / past-simple sentences.
    "i went home",
    "she came back",
    "they left early",
    "we stayed late",
    "i saw you",
    "we heard them",
    "she said yes",
    "he said no",
    "we ate lunch",
    "i drank water",
    "she sang well",
    "he ran fast",
    "they walked slowly",
    "we sat down",
    "i fell down",
    "i found it",
    "we lost it",
    # ``going to`` future phrases.
    "going to bed",
    "going to work",
    "going to school",
    "going to sleep",
    "going to eat",
    "going to play",
    # Possessive-pronoun + noun phrases.
    "my house",
    "your car",
    "his book",
    "her phone",
    "their kids",
    "the dogs bone",
    "the boys name",
    "my name",
    "your name",
    "his name",
    "her name",
    "my friend",
    "your friend",
    "his friend",
    "her friend",
    "my mother",
    "your father",
    "his sister",
    "her brother",
    "my room",
    "your room",
    "my dog",
    "your cat",
    # Place names (DECtalk's text normaliser folds case).
    "paris",
    "tokyo",
    "boston",
    "france",
    "germany",
    "china",
    "canada",
    "europe",
    "asia",
    # Short questions / commands.
    "why me",
    "why now",
    "what now",
    "what next",
    "get up",
    "lie down",
    "look out",
    "stay there",
    "turn around",
    "turn left",
    "turn right",
    # Coordinated noun pairs (body parts / foods).
    "head and shoulders",
    "hands and feet",
    "eyes and ears",
    "arms and legs",
    "coffee and tea",
    "pizza and pasta",
    "cake and cookies",
    "rice and beans",
    # ``-IFY`` verbs (LTS-fallback stem-strip path: stem + IX+F+AY).
    "modify",
    "amplify",
    "simplify",
    "testify",
    "magnify",
    "notify",
    # Spell-out acronyms with all-letters-primary-stressed (the
    # default C path, vs FBI which is special-cased in C's main dic
    # with a destressed middle letter).
    "DNA",
    "USB",
    "PDF",
    "GPS",
    "ATM",
    "DVD",
    "BBC",
    "GDP",
    "HBO",
    "HIV",
    "JFK",
    "LCD",
    "LED",
    "MBA",
    "MRI",
    "NBA",
    "NBC",
    "NFL",
    "PPE",
    "PSA",
    "RPM",
    "SEC",
    "SUV",
    "USC",
    "VIP",
    # 2-letter spell-out acronyms.
    "AC",
    "DC",
    "EU",
    "FM",
    "GM",
    "IT",
    "JS",
    "KP",
    "ML",
    "OK",
    "PR",
    "TM",
    "US",
    "VR",
    "XL",
    # Round 7: longer sentences, time/space, common phrases.
    "the boy and the girl played",
    "i have been to the store",
    "she has been working hard",
    "they have been here all day",
    "i went to the doctor yesterday",
    "we will see you tomorrow at noon",
    "the cars drove down the road",
    "i have ten cats",
    "we ate five apples",
    "she bought three books",
    "we walked for two hours",
    "i have one cat",
    "i have two dogs",
    "we ate four apples",
    "she bought six books",
    "we walked for three hours",
    "in january",
    "in february",
    "in march",
    "in april",
    "in may",
    "in june",
    "in september",
    "in october",
    "in november",
    "next monday",
    "last friday",
    "next tuesday",
    "last monday",
    "next wednesday",
    "next thursday",
    "next friday",
    "next saturday",
    "next sunday",
    "last tuesday",
    "last wednesday",
    "last thursday",
    "last saturday",
    "last sunday",
    "on monday",
    "on tuesday",
    "on wednesday",
    "on thursday",
    "on friday",
    "on saturday",
    "on sunday",
    "don't go",
    "don't stop",
    "don't run",
    "don't cry",
    "don't move",
    "don't talk",
    "don't sleep",
    "don't eat",
    "don't sit",
    "do not stop",
    "do not run",
    "do not go",
    "do not move",
    "do not talk",
    "i'm fine",
    "i'm tired",
    "i'm happy",
    "i'm sad",
    "i'm cold",
    "i'm hot",
    "i'm hungry",
    "i'm thirsty",
    "i'm ready",
    "i'm busy",
    "you're tall",
    "you're smart",
    "you're nice",
    "you're kind",
    "you're funny",
    "she's pretty",
    "she's tall",
    "she's smart",
    "she's nice",
    "he's tall",
    "he's smart",
    "he's nice",
    "he's kind",
    "what's up",
    "what's that",
    "where's the door",
    "who's there",
    "what's this",
    "where's the cat",
    "where's the dog",
    "where's the book",
    "what's wrong",
    "what's new",
    "i love coffee",
    "you love tea",
    "she loves music",
    "he loves books",
    "we love our friends",
    "i love tea",
    "i love books",
    "i love food",
    "i love water",
    "she loves coffee",
    "she loves tea",
    "he loves coffee",
    "he loves tea",
    "we love coffee",
    "they love music",
    "in the box",
    "on the chair",
    "beside the door",
    "near the window",
    "in the room",
    "on the floor",
    "under the table",
    "under the chair",
    "behind the door",
    "behind the chair",
    "near the wall",
    "beside the window",
    "i went to the store and bought milk",
    "she went home and slept",
    "i went home and slept",
    "we went home and slept",
    "he went home and slept",
    "as big as a house",
    "as small as a mouse",
    "as fast as light",
    "more than ten",
    "less than five",
    "more than five",
    "less than ten",
    "more than three",
    "as big as a cat",
    "as small as a cat",
    "the cat is sleeping",
    "the dog is barking",
    "the bird is flying",
    "the fish swims",
    "the cow eats grass",
    "the cat sleeps",
    "the dog barks",
    "the bird sings",
    "the cat is jumping",
    "the dog is running",
    "the bird is singing",
    "the cat is eating",
    "the dog is eating",
    "the cat is running",
    "it's raining",
    "it's sunny",
    "it's cloudy",
    "it's snowing",
    "the weather is nice",
    "it's cold",
    "it's hot",
    "it's warm",
    "it's windy",
    "the weather is cold",
    "the weather is hot",
    "the weather is warm",
    "i want pizza",
    "we eat dinner",
    "she drinks water",
    "the food is hot",
    "the soup is cold",
    "i want food",
    "i want water",
    "i want tea",
    "i want coffee",
    "we eat lunch",
    "she drinks tea",
    "she drinks coffee",
    "he drinks water",
    "he drinks tea",
    "the food is cold",
    "the soup is hot",
    "the coffee is hot",
    "the tea is cold",
    "the water is cold",
    "the water is hot",
    # ``-IFY`` verbs unlocked by the AH0+F+stressed-AY -> IX rule
    # (justify is the canonical case: lex AY2 triggers IX where AY0
    # forms like notify / verify keep AX).
    "justify",
    "classify",
    "horrify",
)


__all__ = ["CORPUS"]
