r"""Convert a DECtalk dictionary file into our CMUDict-style lexicon.

Reads the per-language source dictionary (default for US English:
``Dic_us_2002.txt`` — the 2002 revision shipped as the live US
runtime dictionary), decodes each entry's
``WORD,FORMCLASS,DECTALK_PHONEMIC,FC_BITS,FREQ`` row through
:func:`dectalk.dic.dectalk_phonemes_multi.decode_lang`, and writes
a CMUDict-style output that the ``--lexicon`` flag (or
:func:`dectalk.dic.set_extra_lexicon`) can load.

The output preserves the *form-class* column (``N`` for normal,
``P`` for primary, ``S`` for secondary stress) as a ``|P``/``|S``
suffix on the word key. ``N`` is the default and is emitted
without a suffix to keep the file format backward compatible with
the previous build.

Usage::

    uv run python scripts/build_full_lexicon.py \
        --source /tmp/dectalk-source/src/dapi/src/dic/Dic_us_2002.txt \
        --out src/dectalk/data/lexicon_us_full.txt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from dectalk.dic.dectalk_phonemes_multi import decode_lang


def _convert(source_path: Path, lang: str) -> list[tuple[str, str, list[str]]]:
    """Parse one DECtalk dictionary file.

    Returns a list of ``(word_upper, form_class, phonemes)`` tuples in
    source order. Multiple entries for the same word with different
    form-class letters (e.g. the ``record,P,...`` / ``record,S,...``
    noun/verb minimal pair) are kept as separate rows so the lookup
    layer can pick by context.
    """
    out: list[tuple[str, str, list[str]]] = []
    # The non-English dictionaries (fr, de, sp, la) use Latin-1 encoding
    # for accented characters; UTF-8 decoding with errors="replace" loses
    # them. Try Latin-1 first, fall back to UTF-8.
    try:
        text = source_path.read_text(encoding="latin-1")
    except UnicodeDecodeError:
        text = source_path.read_text(encoding="utf-8", errors="replace")
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        parts = line.split(",")
        min_fields = 3  # word, formclass, phonemic, ...
        if len(parts) < min_fields:
            continue
        word = parts[0]
        if not word:
            continue
        # Skip pure-punctuation entries like '!', '?', etc.
        sanitised = "".join(c for c in word if c.isalnum())
        if not sanitised:
            continue
        # Form-class letter: N (normal), P (primary stress), S (secondary).
        # Older Dic_us.txt files only carry "N"; Dic_us_2002.txt adds P/S
        # for noun/verb minimal pairs.
        fc_letter = parts[1].strip().upper() if len(parts) > 1 else "N"
        if fc_letter not in {"N", "P", "S"}:
            fc_letter = "N"
        decoded = decode_lang(parts[2], lang=lang)
        if not decoded:
            continue
        out.append((word.upper(), fc_letter, decoded))
    return out


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: convert one DECtalk dictionary file to ARPABET."""
    parser = argparse.ArgumentParser(
        description="Convert a DECtalk dictionary file to ARPABET lexicon format.",
    )
    parser.add_argument(
        "--source",
        type=Path,
        required=True,
        help="Path to the DECtalk Dic_*.txt source file.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Path to write the ARPABET lexicon to.",
    )
    parser.add_argument(
        "--lang",
        type=str,
        default="us",
        choices=("us", "uk", "fr", "de", "sp", "la"),
        help="Source dictionary language. Selects the per-language phoneme map.",
    )
    args = parser.parse_args(argv)

    if not args.source.exists():
        print(f"error: source not found: {args.source}", file=sys.stderr)
        return 2

    rows = _convert(args.source, lang=args.lang)
    # Sort by word, then by form-class (N before P before S) so the file
    # is deterministic and reproducible.
    fc_order = {"N": 0, "P": 1, "S": 2}
    rows.sort(key=lambda row: (row[0], fc_order.get(row[1], 0)))
    with args.out.open("w", encoding="utf-8") as fh:
        fh.write("# Generated by scripts/build_full_lexicon.py\n")
        fh.write(f"# Source: {args.source}\n")
        fh.write(
            "# Subject to the licence of the source dictionary; keep private unless\n"
            "# you have explicit redistribution permission from the rights holder.\n"
        )
        fh.write(
            "#\n"
            "# Format: WORD[|FC] PHONEME PHONEME ...\n"
            "# FC is the form-class letter: N (default, omitted), P (primary stress,\n"
            "# typically noun in a noun/verb minimal pair), S (secondary stress,\n"
            "# typically verb). Multiple entries for the same WORD with different FC\n"
            "# letters are kept separate so the lookup layer can disambiguate by\n"
            "# context. See dectalk.dic.lexicon for the parser.\n\n"
        )
        for word, fc_letter, phonemes in rows:
            key = word if fc_letter == "N" else f"{word}|{fc_letter}"
            fh.write(f"{key} {' '.join(phonemes)}\n")
    print(f"wrote {len(rows)} entries to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
