r"""Convert the DECtalk 4.2CD ``Dic_us.txt`` into our CMUDict-style lexicon.

Reads ``<source-root>/src/dapi/src/dic/Dic_us.txt``, decodes each
entry's ``WORD,FORMCLASS,DECTALK_PHONEMIC,...`` row through
:func:`dectalk.dic.dectalk_phonemes.decode`, and writes a CMUDict-format
output that the ``--lexicon`` flag (or :func:`dectalk.dic.set_extra_lexicon`)
can load.

Usage::

    uv run python scripts/build_full_lexicon.py \
        --source /tmp/dectalk-source/src/dapi/src/dic/Dic_us.txt \
        --out src/dectalk/data/lexicon_us_full.txt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from dectalk.dic.dectalk_phonemes import decode


def _convert(source_path: Path) -> dict[str, list[str]]:
    """Parse one DECtalk dictionary file and return a CMUDict-style map."""
    out: dict[str, list[str]] = {}
    text = source_path.read_text(encoding="utf-8", errors="replace")
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        parts = line.split(",")
        min_fields = 3  # word, formclass, phonemic, ...
        if len(parts) < min_fields:
            continue
        word = parts[0]
        if not word or not word.replace("-", "").replace("'", "").isalnum():
            # Skip pure-punctuation entries like '!', '?', etc.
            continue
        decoded = decode(parts[2])
        if not decoded:
            continue
        out[word.upper()] = decoded
    return out


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: convert one DECtalk dictionary file to ARPABET."""
    parser = argparse.ArgumentParser(
        description="Convert a DECtalk dictionary file to ARPABET lexicon format.",
    )
    parser.add_argument(
        "--source",
        type=Path,
        required=True,
        help="Path to the DECtalk Dic_*.txt source file.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Path to write the ARPABET lexicon to.",
    )
    args = parser.parse_args(argv)

    if not args.source.exists():
        print(f"error: source not found: {args.source}", file=sys.stderr)
        return 2

    lex = _convert(args.source)
    with args.out.open("w", encoding="utf-8") as fh:
        fh.write("# Generated by scripts/build_full_lexicon.py\n")
        fh.write(f"# Source: {args.source}\n")
        fh.write(
            "# Subject to the licence of the source dictionary; keep private unless\n"
            "# you have explicit redistribution permission from the rights holder.\n\n"
        )
        for word in sorted(lex):
            fh.write(f"{word} {' '.join(lex[word])}\n")
    print(f"wrote {len(lex)} entries to {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
