#!/usr/bin/env python3
"""Regenerate `docs/TASKS.md` from the current state of the codebase.

The task queue lists every Python module under ``src/dectalk/`` that
still raises ``NotImplementedError`` — i.e. is a deferred shim awaiting
the actual port. Each row maps a Python target back to the C source it
mirrors (parsed from the module's own docstring), so an orchestrator
can assign a translator agent with both endpoints in hand.

Format: a Markdown table that translator agents can edit in-place to
claim a task (set the ``Owner`` column to the agent's slug) without
needing JSON parsing. The file regenerates idempotently — claims are
preserved iff this script is re-run after the agent's PR lands and
the shim is replaced. Until then, regeneration will reset claims, so
run it sparingly (typically just before a fan-out batch).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SRC_ROOT = _REPO_ROOT / "src" / "dectalk"
_TASKS_MD = _REPO_ROOT / "docs" / "TASKS.md"


# Match `Translated from ``<path>``` or `Translated from ``<path>`` line N`
# in module docstrings.
_C_SOURCE_RE = re.compile(r"Translated from\s+``([^`]+)``")


def _python_modules_with_shim() -> list[Path]:
    """Every .py file under src/dectalk/ that contains a NotImplementedError raise."""
    results: list[Path] = []
    for path in _SRC_ROOT.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if "raise NotImplementedError" in text:
            results.append(path)
    return sorted(results)


def _c_source_for(module_path: Path) -> str | None:
    """Pull the ``Translated from `...``` reference out of the module docstring."""
    try:
        text = module_path.read_text(encoding="utf-8")
    except OSError:
        return None
    match = _C_SOURCE_RE.search(text)
    return match.group(1) if match else None


def _stage_for(module_path: Path) -> str:
    """Best-effort stage tag based on the module's directory under src/dectalk/."""
    try:
        rel = module_path.relative_to(_SRC_ROOT)
    except ValueError:
        return "?"
    parts = rel.parts
    if len(parts) >= 2:  # noqa: PLR2004
        return parts[0]
    return "?"


def _render_table(modules: list[Path]) -> str:
    rows: list[str] = []
    rows.append("| C source | Python target | Stage | Status | Owner |")
    rows.append("|---|---|---|---|---|")
    for mod in modules:
        c_source = _c_source_for(mod) or "—"
        py_rel = mod.relative_to(_REPO_ROOT)
        stage = _stage_for(mod)
        rows.append(f"| `{c_source}` | `{py_rel}` | {stage} | open | — |")
    return "\n".join(rows)


def _render_document(modules: list[Path]) -> str:
    header = """\
# Porting task queue

Auto-generated by `scripts/refresh_tasks.py`. **Do not edit by hand
except to claim a task** — re-running the script will overwrite the
table while preserving the structure.

To claim a task, set its `Owner` cell to your agent slug (e.g.
`@claude-ph-1`). Orchestrators dispatching translator agents check
the table to avoid double-assignment.

When a port lands and the Python shim no longer raises
`NotImplementedError`, the next regeneration removes the row.

See `docs/PORTING.md` for the per-task playbook and acceptance
checklist, and `docs/PLAN.md` for strategic phase context.

## Open ports

"""
    return header + _render_table(modules) + "\n"


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: regenerate or check `docs/TASKS.md`."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated content to docs/TASKS.md; exit non-zero if drifted",
    )
    args = parser.parse_args(argv)

    modules = _python_modules_with_shim()
    new_content = _render_document(modules)

    if args.check:
        if not _TASKS_MD.exists():
            print("docs/TASKS.md missing — run without --check to create it", file=sys.stderr)
            return 2
        existing = _TASKS_MD.read_text(encoding="utf-8")
        if existing != new_content:
            print("docs/TASKS.md is out of date; run scripts/refresh_tasks.py", file=sys.stderr)
            return 1
        print("docs/TASKS.md up to date")
        return 0

    _TASKS_MD.parent.mkdir(parents=True, exist_ok=True)
    _TASKS_MD.write_text(new_content, encoding="utf-8")
    print(f"wrote {_TASKS_MD} ({len(modules)} open ports)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
