"""Lexicon (word -> ARPABET phonemes) loader.

Two-tier bundled lexicon: prefers ``src/dectalk/data/lexicon_<lang>_full.txt``
(generated by ``scripts/build_full_lexicon.py``) when present, falling
back to the small starter ``lexicon_<lang>.txt`` shipped in this repo.

Format for both: one entry per line, ``WORD[|FC] PHONEME PHONEME ...``.
Lines beginning with ``#`` are comments. Blank lines are skipped.

The optional ``|FC`` suffix on the word records the DECtalk source
dictionary's *form-class* letter:

- ``N`` (default; omitted when no suffix is present) — normal entry.
- ``P`` — primary-stress form (typically the noun in a noun/verb
  minimal pair such as ``record,P`` → ``r'EkRd``).
- ``S`` — secondary-stress form (typically the verb, e.g.
  ``record,S`` → ``r|k'ord``).

The legacy CMUDict-style format (``WORD PHONEMES...`` with no
``|FC`` suffix) is fully supported — every such row is treated as
an ``N`` entry. Multiple rows for the same ``WORD`` with different
form classes coexist in the loaded mapping under their unique
``WORD|FC`` keys; the bare ``WORD`` key resolves to the default
reading (``N`` if present, else ``P``, else any).
:func:`dectalk.dic.lookup` exposes an optional ``form_class``
argument to pick a specific homograph reading.
"""

from __future__ import annotations

from importlib import resources
from pathlib import Path
from typing import Final

# Per-language bundled lexicon filenames. ``_full`` files are produced by
# ``scripts/build_full_lexicon.py`` from the DECtalk source; ``_mini``
# files are the small starter sets always shipped in this repo.
_LEXICON_FILES: Final[dict[str, tuple[str, ...]]] = {
    # The loader tries each filename in order and uses the first that exists.
    "us": ("lexicon_us_full.txt", "lexicon_us.txt"),
    "uk": ("lexicon_uk_full.txt", "lexicon_uk.txt"),
    "sp": ("lexicon_sp_full.txt",),
    "la": ("lexicon_la_full.txt",),
    "fr": ("lexicon_fr_full.txt",),
    "de": ("lexicon_de_full.txt",),
}

# Legacy aliases retained for backward compatibility with any external code
# that imports these names.
_BUILTIN_LEXICON_RESOURCE: Final[str] = "lexicon_us.txt"
_UK_OVERRIDE_RESOURCE: Final[str] = "lexicon_uk.txt"

# Recognised form-class letters (Dic_us_2002.txt column 2). Anything else
# is normalised to ``N``.
_VALID_FC: Final[frozenset[str]] = frozenset({"N", "P", "S"})

# Preference order when callers don't request a specific form-class: the
# default (``N``) wins, then primary (``P`` — the noun in a noun/verb pair
# tends to be the more frequent reading in isolation), then secondary.
_FC_PREFERENCE: Final[tuple[str, ...]] = ("N", "P", "S")


def load_text_lexicon(path: str | Path) -> dict[str, list[str]]:
    """Parse a CMUDict-style text lexicon.

    Args:
        path: Path to a text file with one ``WORD[|FC] PHONEME PHONEME ...``
            entry per line. Comments start with ``#``; blank lines skipped.

    Returns:
        Mapping from upper-cased word to its phoneme list. Form-class
        homographs are keyed as ``WORD|P`` / ``WORD|S``; the bare
        ``WORD`` key resolves to the default reading (the ``N`` entry
        if present, else the most-preferred form-class seen).

    Raises:
        FileNotFoundError: If ``path`` does not exist.
        ValueError: If a non-comment line has fewer than 2 whitespace-
            separated tokens (a word and at least one phoneme).
    """
    text = Path(path).read_text(encoding="utf-8")
    return _parse_lexicon_text(text)


def load_builtin_lexicon(*, lang: str = "us") -> dict[str, list[str]]:
    """Parse the bundled lexicon shipped with the dectalk package.

    The loader prefers the larger generated ``lexicon_<lang>_full.txt``
    file when present and falls back to the smaller starter
    ``lexicon_<lang>.txt`` otherwise. UK requests additionally layer
    ``lexicon_uk.txt`` (the small RP overrides) on top of the US base
    when the full UK file is unavailable.

    Args:
        lang: Language tag. Supported values match the keys of
            :data:`_LEXICON_FILES` (currently ``"us"`` and ``"uk"``).

    Returns:
        Mapping from upper-cased word to its phoneme list. The returned
        dict is freshly built each call so callers can mutate it freely.

    Raises:
        ValueError: If ``lang`` is not a recognised language tag.
    """
    if lang not in _LEXICON_FILES:
        raise ValueError(f"unknown lang {lang!r}; supported values: {sorted(_LEXICON_FILES)}")

    candidates = _LEXICON_FILES[lang]
    # Use the first candidate that exists. The full variant is preferred
    # when present; otherwise fall through to the bundled mini list.
    for resource_name in candidates:
        text = _try_read_resource(resource_name)
        if text is not None:
            base = _parse_lexicon_text(text)
            return _layer_uk_overrides(base, lang)

    raise FileNotFoundError(f"no bundled lexicon found for lang={lang!r}; tried {candidates}")


def _try_read_resource(name: str) -> str | None:
    """Read a packaged data file, returning None if it does not exist."""
    resource = resources.files("dectalk.data").joinpath(name)
    if not resource.is_file():
        return None
    return resource.read_text(encoding="utf-8")


def _layer_uk_overrides(base: dict[str, list[str]], lang: str) -> dict[str, list[str]]:
    """When asked for UK and the full UK file isn't present, layer the small overrides."""
    if lang != "uk":
        return base
    # If we already loaded `lexicon_uk_full.txt` the base is already UK; no-op.
    # Otherwise we loaded `lexicon_uk.txt` (the small override file) — but
    # that's only useful when stacked on the US base, so do that here.
    full_uk = _try_read_resource(_LEXICON_FILES["uk"][0])
    if full_uk is not None:
        return base
    us_text = _try_read_resource(_LEXICON_FILES["us"][1]) or _try_read_resource(
        _LEXICON_FILES["us"][0]
    )
    if us_text is None:
        return base
    merged = _parse_lexicon_text(us_text)
    merged.update(base)
    return merged


def _split_word_fc(token: str) -> tuple[str, str]:
    """Split a ``WORD[|FC]`` token into ``(word, fc_letter)``.

    Unrecognised FC letters fall back to ``N`` (default). The
    returned ``word`` is upper-cased.
    """
    if "|" not in token:
        return token.upper(), "N"
    word, _, fc = token.partition("|")
    fc_letter = fc.strip().upper()
    if fc_letter not in _VALID_FC:
        fc_letter = "N"
    return word.upper(), fc_letter


def _parse_lexicon_text(text: str) -> dict[str, list[str]]:
    """Internal parser; public callers should use the loaders above.

    Each non-comment line is ``WORD[|FC] PHONEME PHONEME ...``. The
    returned mapping always carries a bare ``WORD`` key (the default
    reading — N-class if present, else the most-preferred FC seen)
    plus ``WORD|P`` / ``WORD|S`` keys for any non-default form-class
    homographs. Callers that only need the default reading can ignore
    the suffixed keys.
    """
    lex: dict[str, list[str]] = {}
    # Track which FC letter currently fills the bare key, so a later
    # N-class row can promote over an earlier P/S row.
    bare_fc: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        min_tokens = 2  # word + at least one phoneme
        if len(parts) < min_tokens:
            raise ValueError(f"malformed lexicon line: {raw_line!r}")
        word, fc_letter = _split_word_fc(parts[0])
        phonemes = parts[1:]
        if fc_letter != "N":
            lex[f"{word}|{fc_letter}"] = phonemes
        # Maintain the bare key per the preference order. The first row
        # seen wins unless a later row carries a strictly more preferred
        # FC letter.
        current = bare_fc.get(word)
        if current is None or _FC_PREFERENCE.index(fc_letter) < _FC_PREFERENCE.index(current):
            lex[word] = phonemes
            bare_fc[word] = fc_letter
    return lex
