"""Compound-marker, VPSTART, and form-class sidecar loaders.

Three sidecar tables, generated by ``scripts/build_dic_sidecars.py``
from the DECtalk source ``Dic_us.txt``, sit alongside the bundled
lexicon:

- ``lexicon_us_markers.txt`` — for words whose dictionary entry carries
  one or more ``*`` MBOUND markers (closed compounds such as
  ``BREAKFAST``, ``PIPELINE``, ``DATABASE``). Stored as upper-cased
  word + ARPABET phoneme list with literal ``__PUNCT__*`` tokens
  preserved at each compound boundary. :func:`load_marker_lexicon`
  parses the file once per process.

- ``vpstart_us.txt`` — one upper-cased word per line whose form-class
  mask satisfies the C VPSTART rule from
  ``src/dapi/src/lts/ls_dict.c`` lines 759-763
  ((``fc & (FC_VERB|FC_CHARACTER)) == (FC_VERB|FC_CHARACTER)`` or
  ``fc == FC_VERB``). :func:`load_vpstart_words` returns a frozenset.
  Paired ``P``/``S`` homographs are excluded — their ``)`` emission
  depends on which entry the disambiguator selects, so the caller
  applies :func:`emits_vpstart` to the selected entry's mask instead.

- ``formclass_us.txt`` — ``WORD[|P|S] <hex mask>`` rows carrying the
  built form-class mask of every dictionary entry (the runtime
  ``dtalk_us.dic`` masks: the source column plus the ``dic_comm.c``
  homograph flags). :func:`load_formclass_lexicon` parses the file
  once per process; the homograph disambiguator (issue #295) reads
  both the ``WORD|P`` / ``WORD|S`` entry masks and the bare ``WORD``
  masks of the neighbouring context words from it.

All loaders return empty containers when the sidecar file is absent so
out-of-tree builds (e.g. the bundled-data sdist without sidecars) keep
working.
"""

from __future__ import annotations

from importlib import resources
from typing import Final

from dectalk.dic.form_class_bits import FC_CHARACTER, FC_VERB

_VPHRASE: Final[int] = FC_VERB | FC_CHARACTER
"""``VPHRASE`` from ``src/dapi/src/lts/ls_defs.h`` line 658."""


def emits_vpstart(fc_mask: int) -> bool:
    """True iff an entry with this built form-class mask emits ``)``.

    Mirrors the VPSTART condition in ``src/dapi/src/lts/ls_dict.c``
    lines 759-763::

        ((fc & VPHRASE) == VPHRASE) || fc == FC_VERB

    evaluated on the *built* mask (homograph flags included). A
    selected secondary homograph entry therefore never fires — its
    ``FC_HOMOGRAPH`` bit breaks the ``fc == FC_VERB`` equality — while
    a pure-verb primary entry fires via the ``VPHRASE`` containment
    (its build-time ``FC_CHARACTER`` flag completes the mask). Both
    behaviours are verified against the C oracle (issue #295).

    Args:
        fc_mask: Built form-class mask of the dictionary entry that
            will be spoken (for homographs: the entry the
            disambiguator selected).

    Returns:
        Whether the C dictionary emitter would send the ``)``
        (VPSTART) phoneme before this entry's phonemes.
    """
    return (fc_mask & _VPHRASE) == _VPHRASE or fc_mask == FC_VERB


def _try_read_resource(name: str) -> str | None:
    """Read a packaged data file under ``dectalk.data``; return None if absent."""
    resource = resources.files("dectalk.data").joinpath(name)
    if not resource.is_file():
        return None
    return resource.read_text(encoding="utf-8")


def _parse_marker_lexicon_text(text: str) -> dict[str, list[str]]:
    """Parse the marker-lexicon sidecar text into ``{word: phonemes}``."""
    lex: dict[str, list[str]] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        min_tokens = 2  # word + at least one phoneme/marker
        if len(parts) < min_tokens:
            continue
        word = parts[0].upper()
        phonemes = parts[1:]
        lex[word] = phonemes
    return lex


def _parse_vpstart_text(text: str) -> frozenset[str]:
    """Parse the VPSTART sidecar text into a frozenset of upper-cased words."""
    words: set[str] = set()
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        words.add(line.upper())
    return frozenset(words)


def _parse_formclass_text(text: str) -> dict[str, int]:
    """Parse the form-class sidecar text into ``{key: mask}``.

    Keys are ``WORD`` for ordinary entries and ``WORD|P`` / ``WORD|S``
    for the two entries of a homograph pair; masks are the built
    form-class values (hex in the file).
    """
    table: dict[str, int] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        expected_tokens = 2  # key + hex mask
        if len(parts) != expected_tokens:
            continue
        try:
            table[parts[0].upper()] = int(parts[1], 16)
        except ValueError:
            continue
    return table


_MARKER_LEXICON_CACHE: dict[str, dict[str, list[str]]] = {}
_VPSTART_CACHE: dict[str, frozenset[str]] = {}
_FORMCLASS_CACHE: dict[str, dict[str, int]] = {}

_MARKER_LEXICON_FILES: Final[dict[str, str]] = {
    "us": "lexicon_us_markers.txt",
}

_VPSTART_FILES: Final[dict[str, str]] = {
    "us": "vpstart_us.txt",
}

_FORMCLASS_FILES: Final[dict[str, str]] = {
    "us": "formclass_us.txt",
}


def load_marker_lexicon(*, lang: str = "us") -> dict[str, list[str]]:
    """Return the compound-marker sidecar lexicon for ``lang``.

    Cached: the file is parsed once on the first call per language and
    the resulting dict is reused thereafter. Callers receive a reference
    to the cached dict — treat the return value as read-only.

    Args:
        lang: Language tag. Currently only ``"us"`` ships a sidecar;
            other languages return an empty dict.

    Returns:
        Mapping from upper-cased word to its ARPABET phoneme list with
        ``__PUNCT__*`` tokens preserved at compound boundaries. Empty
        when the sidecar file is absent or ``lang`` is unsupported.
    """
    if lang in _MARKER_LEXICON_CACHE:
        return _MARKER_LEXICON_CACHE[lang]
    filename = _MARKER_LEXICON_FILES.get(lang)
    if filename is None:
        _MARKER_LEXICON_CACHE[lang] = {}
        return _MARKER_LEXICON_CACHE[lang]
    text = _try_read_resource(filename)
    if text is None:
        _MARKER_LEXICON_CACHE[lang] = {}
        return _MARKER_LEXICON_CACHE[lang]
    _MARKER_LEXICON_CACHE[lang] = _parse_marker_lexicon_text(text)
    return _MARKER_LEXICON_CACHE[lang]


def load_vpstart_words(*, lang: str = "us") -> frozenset[str]:
    """Return the VPSTART-eligible word set for ``lang``.

    Cached: the file is parsed once on the first call per language.

    Args:
        lang: Language tag. Currently only ``"us"`` ships a sidecar;
            other languages return an empty frozenset.

    Returns:
        Frozenset of upper-cased words whose dictionary form-class mask
        satisfies the C VPSTART rule. Empty when the sidecar file is
        absent or ``lang`` is unsupported.
    """
    if lang in _VPSTART_CACHE:
        return _VPSTART_CACHE[lang]
    filename = _VPSTART_FILES.get(lang)
    if filename is None:
        _VPSTART_CACHE[lang] = frozenset()
        return _VPSTART_CACHE[lang]
    text = _try_read_resource(filename)
    if text is None:
        _VPSTART_CACHE[lang] = frozenset()
        return _VPSTART_CACHE[lang]
    _VPSTART_CACHE[lang] = _parse_vpstart_text(text)
    return _VPSTART_CACHE[lang]


def load_formclass_lexicon(*, lang: str = "us") -> dict[str, int]:
    """Return the built form-class mask table for ``lang``.

    Cached: the file is parsed once on the first call per language and
    the resulting dict is reused thereafter. Callers receive a
    reference to the cached dict — treat the return value as
    read-only.

    Args:
        lang: Language tag. Currently only ``"us"`` ships a sidecar;
            other languages return an empty dict.

    Returns:
        Mapping from ``WORD`` (ordinary entries) and ``WORD|P`` /
        ``WORD|S`` (homograph pair entries) to the built form-class
        mask embedded in the runtime dictionary. Empty when the
        sidecar file is absent or ``lang`` is unsupported.
    """
    if lang in _FORMCLASS_CACHE:
        return _FORMCLASS_CACHE[lang]
    filename = _FORMCLASS_FILES.get(lang)
    if filename is None:
        _FORMCLASS_CACHE[lang] = {}
        return _FORMCLASS_CACHE[lang]
    text = _try_read_resource(filename)
    if text is None:
        _FORMCLASS_CACHE[lang] = {}
        return _FORMCLASS_CACHE[lang]
    _FORMCLASS_CACHE[lang] = _parse_formclass_text(text)
    return _FORMCLASS_CACHE[lang]


__all__ = [
    "emits_vpstart",
    "load_formclass_lexicon",
    "load_marker_lexicon",
    "load_vpstart_words",
]
