"""Bit-parity tests for :func:`dectalk.api.mulaw.LinearToMuLaw`.

Reference vectors generated by faithfully simulating the C source
body in Python. These cover the four corners of the input range, a
few mid-range values, and the clip behaviour at +/- MULAW_CLIP_LEVEL.
"""

from __future__ import annotations

from dectalk.api.mulaw import LinearToMuLaw, MULAW_BIAS, MULAW_CLIP_LEVEL


def _c_reference(w_sample: int) -> int:
    """Re-implement the C body inline; used as a golden oracle."""
    # Static C LUT (same as the production module).
    lut = (
        [0] * 2 + [1] * 2 + [2] * 4 + [3] * 8 + [4] * 16
        + [5] * 32 + [6] * 64 + [7] * 128
    )
    sign = (w_sample >> 8) & 0x80
    if sign != 0:
        w_sample = -w_sample
    if w_sample > MULAW_CLIP_LEVEL:
        w_sample = MULAW_CLIP_LEVEL
    w_sample = w_sample + MULAW_BIAS
    exponent = lut[(w_sample >> 7) & 0xFF]
    mantissa = (w_sample >> (exponent + 3)) & 0x0F
    return (~(sign | (exponent << 4) | mantissa)) & 0xFF


def test_zero_sample() -> None:
    assert LinearToMuLaw(0) == _c_reference(0)


def test_positive_clip_level() -> None:
    """Saturates at +MULAW_CLIP_LEVEL."""
    assert LinearToMuLaw(MULAW_CLIP_LEVEL) == _c_reference(MULAW_CLIP_LEVEL)


def test_negative_clip_level() -> None:
    """Saturates at -MULAW_CLIP_LEVEL."""
    assert LinearToMuLaw(-MULAW_CLIP_LEVEL) == _c_reference(-MULAW_CLIP_LEVEL)


def test_positive_one() -> None:
    assert LinearToMuLaw(1) == _c_reference(1)


def test_negative_one() -> None:
    assert LinearToMuLaw(-1) == _c_reference(-1)


def test_sweep_matches_c_body() -> None:
    """Sweep the full 16-bit signed range; every sample matches the C reference."""
    for s in range(-32768, 32768, 137):  # step 137 covers ~478 samples
        assert LinearToMuLaw(s) == _c_reference(s), f"mismatch at sample={s}"


def test_exhaustive_low_amplitude() -> None:
    """Exhaustive check across the most sensitive range."""
    for s in range(-256, 256):
        assert LinearToMuLaw(s) == _c_reference(s), f"mismatch at sample={s}"
